### PR TITLE
Fix/texts

### PR DESCRIPTION
**Pull request by criadoperez**
## Related Issues
No issue opened

## Proposed Changes
Multiple typos on files

### CODE REVIEW

**Review by fridrik01 — COMMENTED** [review]
You need to run "make gen" to address the failing CI test

**Comment by criadoperez** [comment]
When I run `make gen` I get the following error that it can't find goimports. Can you please guide me on the right direction to fix this?


```bash
chain/actors/policy/policy.go
itests/kit/ensemble_opts_nv.go
go run ./gen/api
goimports -w api
bash: line 1: goimports: command not found
make: *** [Makefile:308: api-gen] Error 127
```

So then installed goimports with `go install golang.org/x/tools/cmd/goimports@latest` but didn't solve the problem.

Then when trying to install goimports with `go get` I get an error:
```bash
# go get -v golang.org/x/tools/cmd/goimports
go: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20220519234331-bfd1f5f9fe38 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /go/filecoin-project_lotus/extern/filecoin-ffi/go.mod: no such file or directory
```

So finally I built and installed goimports from source which made `goimports` work but `make gen` now produces the following error:
```bash
go run ./gen/api
goimports -w api
goimports -w api
go run ./gen/main.go
chain/consensus/utils.go:12:2: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20220519234331-bfd1f5f9fe38 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /root/filecoin-project_lotus/extern/filecoin-ffi/go.mod: no such file or directory
chain/vm/fvm.go:21:2: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20220519234331-bfd1f5f9fe38 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /root/filecoin-project_lotus/extern/filecoin-ffi/go.mod: no such file or directory
make: *** [Makefile:288: type-gen] Error 1
```

**Comment by fridrik01** [comment]
> When I run `make gen` I get the following error that it can't find goimports. Can you please guide me on the right direction to fix this?

After installing goimports with go install, you need to make sure its install location is in your $PATH. You can run `go env` and sees where that location is under GOPATH. It should probably be in your HOME directory so usually you would just add `$HOME/go/bin` to your PATH.

**Comment by criadoperez** [comment]
After running `make gen` no files are modified. 
However I then ran `make docsgen-cli` which did. Committing these changes.

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
