### PR TITLE
build: release: v1.27.1-rc2

### PR DESCRIPTION
**Pull request by rjan90**
Prepping the second release candidate of v1.27.1

## Proposed Changes
Some backports added:
- https://github.com/filecoin-project/lotus/pull/12086 
- Additional cleanups of legacy-markets code (https://github.com/filecoin-project/lotus/pull/12084, https://github.com/filecoin-project/lotus/pull/12095, https://github.com/filecoin-project/lotus/pull/12100)
- https://github.com/filecoin-project/lotus/pull/11905 (tested and speeds up the `eth_call` considerably) 
- https://github.com/filecoin-project/lotus/pull/12090

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [ x PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
> @rjan90 we really should add https://github.com/filecoin-project/lotus/pull/12100

Feel free to add the release/backport labels to PRs you belive is worth backporting, then its a lot easier to 👀 in the merged PRs since the release.

**Comment by ZenGround0** [comment]
I tagged #12090 as release/backport too.  Lmk if you have any issues with including that one @rjan90

**Comment by ZenGround0** [comment]
> Feel free to add the release/backport labels to PRs you belive is worth backporting, then its a lot easier to 👀 in the merged PRs since the release

@rjan90 unfortunately @ribasushi doesn't have the right permissions to apply labels.

**Comment by rjan90** [comment]
> I tagged https://github.com/filecoin-project/lotus/pull/12090 as release/backport too. Lmk if you have any issues with including that one @rjan90

Added it to the release-🚝 now!

**Comment by rjan90** [comment]
@ZenGround0 Do you mind giving this a review now that 12090 has been backported?

**Review by rvagg — APPROVED** [review]

**Review by jennijuju — APPROVED** [review]

**Pull request merged**
