### PR TITLE
chore: merge v1.28.1 release back to master & update master version to v1.28.2-dev

### PR DESCRIPTION
**Pull request by jennijuju**

### CODE REVIEW

**Review by rvagg — APPROVED** [review]

**Review by rjan90 — APPROVED** [review]

**Comment by rvagg** [comment]
mmm, https://github.com/filecoin-project/lotus/pull/12271 includes the commit (PR) that was supposed to change it https://github.com/filecoin-project/lotus/pull/12276 but it seems to have got lost for the 1.28.0 final. So `releases` and the 1.28.x releases have e467d2992e3f9bd0 but master has d041c9ab85e68cfb

Thankfully the difference is minimal and not material: https://github.com/filecoin-project/filecoin-ffi/compare/e467d2992e3f9bd0...d041c9ab85e68cfb

But master is on d041c9ab85e68cfb, which is https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.28.0, which is what we want. We just happened to release 1.28.0 and 1.28.1 with https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.28.0-rc2

A concern, and another reason we need to bail on the complicated merge, mega-squash, multi-branch dance I think. But not fatal to the releases. We have the right ref-fvm and proofs versions.

**Comment by rjan90** [comment]
> 🚨 the FFI does not agree on both ends

1. `d041c9ab85e68cfb57daf5fbaedeeee0f72cb5ad` corresponds to https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.28.0.
2. `e467d2992e3f9bd09beb71ecf84323b45d2a3511` corresponds to https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.28.0-rc2

Chain of events:
1. `d041c`-FFI updated in master here https://github.com/filecoin-project/lotus/pull/12276
2. The https://github.com/filecoin-project/lotus/pull/12276 PR was listed and backported to the `release/v1.28.0` branch as part of the final prep: https://github.com/filecoin-project/lotus/pull/12271/commits/5afd10af09d4fb36d443e09c84adcbc50f00cb4b. But the `extern/filecoin-ffi` change did not get included in that backport.

Both FFI-versions are good for nv23, and the `e467d`-FFI (v1.28.0-rc2) is the one that was used during Calibration network upgrade, and no changes related to nv23 has landed between those versions as seen by the [v1.28.0-rc2...v1.28.0](https://github.com/filecoin-project/filecoin-ffi/compare/v1.28.0-rc2...v1.28.0).

That said, it's not good that I missed that `extern/filecoin-ffi` was not included in the backport for the final prep of v1.28.0. And that we did not caught it during review. I will add it as an item during nv23-retro and discussions on [branch names/merges we use](https://github.com/filecoin-project/lotus/issues/12072#issuecomment-2249071620), as this would have been bad in the case where the Filecoin-FFI actually needed change.
- One initial though here is having a GHA-bot that comments if there is a diff between the `extern/filecoin-ffi` hash in their PR, and the one in the master branch.

**Comment by rvagg** [comment]
(and this PR is correct to not pull a change back in btw)

**Comment by rvagg** [comment]
Oh, and yet another reason to get the ffi prebuilds work done!

**Comment by BigLep** [comment]
Concerning FFI not agreeing on both ends and [the explanation](https://github.com/filecoin-project/lotus/pull/12306#issuecomment-2249916531), this is inevitable I think with our consistent setup.  Items around standardizing how we commit, standardizing how we backport, etc. are observations I've been jotting down in https://docs.google.com/document/d/11jN9E4IcgcbU_6acAIHuh29v7yGFj7OHiiGYpoUuSEs/edit?pli=1#heading=h.qkulnat42emv .  Others feel free to put in lessons learned as well.  These seem like some of the quickest low hanging fruit to address after the network upgrade.

I also in future would expect to see a clearer commit history.  I think ideally every (or close to every) commit would list its assocated PR in the commit message.  (We get some of that by default if there is more squash and merge happening.)

**Comment by rvagg** [comment]
done in https://github.com/filecoin-project/lotus/pull/12317

**Pull request closed without merging**
