### PR TITLE
chore: update filecoin-ffi to v1.30.0-rc1

### PR DESCRIPTION
**Pull request by rjan90**
## Proposed Changes
Update filecoin-ffi to v1.30.0-rc1

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [x] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [x] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [x] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Review by rvagg — CHANGES_REQUESTED** [review]
I suggest we hold off until https://github.com/filecoin-project/filecoin-ffi/issues/491 is resolved since this doesn't move us much closer to not requiring a recompile

**Comment by BigLep** [comment]
@rjan90 : can you merge once https://github.com/filecoin-project/filecoin-ffi/pull/492 is merged?

**Comment by rjan90** [comment]
I have bumped the filecoin-ffi version to v1.30.0-rc1 in this commit: https://github.com/filecoin-project/lotus/pull/12476/commits/30142aeaebe3095c037d9fd0ba7a7e3e2ffce057, which should unblock us needing to recompile.

**Review by rvagg — APPROVED** [review]
👌 confirmed that this does download pre-compiled binaries

**Pull request merged**
