### PR TITLE
chore: Remove the test-vectors submodule

### PR DESCRIPTION
**Pull request by shrenujbansal**
## Proposed Changes

Remove test-vectors submodule as its no longer required

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [x] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [x] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [x] Tests exist for new functionality or change in behavior
- [x] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
> Remove test-vectors submodule as its no longer required

Providing some more context here why this was needed. When users was upgrading from v1.23.3 --> v1.23.4-rc1, they where unable the update `extern/test-vectors` due to: https://github.com/filecoin-project/lotus/pull/11196, by following the upgrade-in place process. When getting to the `git submodule update` step, you encounter:

```
git submodule update    
Submodule path 'extern/filecoin-ffi': checked out 'bf5edd551d23901fa565aac4ce94433afe0c278e'
warning: unable to rmdir 'gen/extern/fil-blst': Directory not empty
warning: unable to rmdir 'gen/extern/filecoin-ffi': Directory not empty
Submodule path 'extern/test-vectors': checked out '195bc065973ec35826621823964a5c3cbe5fa56d'
```

This causes v1.23.4-rc1 to be reported as `.dirty`, which may cause user confusion that something has gone wrong with the upgrade.

Testing this locally by cherry-picking the two commits resolved the ability to get rid of the `extern/test-vectors`.

**Review by magik6k — APPROVED** [review]

**Comment by arajasek** [comment]
@shrenujbansal Please provide more info in PR descriptions.

> Remove test-vectors submodule as its no longer required

They are still required, they ensure historical consensus isn't broken. This isn't the most important thing, but is something we _should_ keep if we can.

> Providing some more context here why this was needed. When users was upgrading from v1.23.3 --> v1.23.4-rc1, they where unable the update `extern/test-vectors` due to: #11196, by following the upgrade-in place process. When getting to the `git submodule update` step, you encounter:
> 
> ```
> git submodule update    
> Submodule path 'extern/filecoin-ffi': checked out 'bf5edd551d23901fa565aac4ce94433afe0c278e'
> warning: unable to rmdir 'gen/extern/fil-blst': Directory not empty
> warning: unable to rmdir 'gen/extern/filecoin-ffi': Directory not empty
> Submodule path 'extern/test-vectors': checked out '195bc065973ec35826621823964a5c3cbe5fa56d'
> ```
> 
> This causes v1.23.4-rc1 to be reported as `.dirty`, which may cause user confusion that something has gone wrong with the upgrade.

@rjan90 Thanks for the context here! I understand the problem, but I think we should simply communicate this change to users. Do you think it'd be okay to just tell users to run `rm -rf gen/extern/fil-blst && rm -rf gen/extern/filecoin-ffi` as part of this update? I don't know of a nicer way to get git to force the delete, but maybe someone else does?

**Comment by rjan90** [comment]
@arajasek Happy to go with either approach (I.e call-out in changelog). I try out the rm -rf way, else we can also just ask people to clone a fresh repo before updating to v1.23.4 to prevent the `.dirty` build

**Comment by rjan90** [comment]
So `rm -rf gen/extern/fil-blst && rm -rf gen/extern/filecoin-ffi` does help with getting rid of the untracked changes in `extern/test-vectors`. So I will just add a call out that users should clone a new Lotus repo as part of the upgrade.

**Comment by arajasek** [comment]
> So `rm -rf gen/extern/fil-blst && rm -rf gen/extern/filecoin-ffi` does not help with getting rid of the untracked changes in `extern/test-vectors`. So I will just add a call out that users should clone a new Lotus repo as part of the upgrade.

Really? If you run `git submodule update && rm -rf gen/extern/fil-blst && rm -rf gen/extern/filecoin-ffi`, it's still dirty?

**Comment by rjan90** [comment]
Yes, extern/test-vectors still show up with:
Screenshot 2023-09-23 at 09 14 48

**Comment by rjan90** [comment]
Closing this PR, since we went with the approach of asking users to clone a new repo when upgrading to v1.25.0 to prevent them from getting a `.dirty` build.

**Pull request closed without merging**
