### PR TITLE
modify quantile imports error (go-v1.18.0)

### PR DESCRIPTION
**Pull request by koalacxr**
## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

### CODE REVIEW

**Comment by koalacxr** [comment]
update to go v1.18.0

**Review by magik6k — COMMENTED** [review]
CI seems to be quite unhappy

**Review by magik6k — APPROVED** [review]
Thanks for the PR!

**Comment by silvianetobessa** [comment]
Hello @koalacxr!

This contribution to the Filecoin codebase was voted as impactful during Q1 and is eligible for a FIL prize as part of a Protocol Labs experiment to reward open source contributions from the community (see[ full details here](https://filecoin.io/blog/posts/a-public-goods-experiment-on-filecoin-retroactively-funding-impact-with-quadratic-voting/)).

Please reach out to us through commons@protocol.ai to receive the instructions on how to claim your reward!

**Comment by koalacxr** [comment]
Hello @silvianetobessa  
My Email is koalaone@gmail.com. The Email has been sent.

**Pull request merged**
