### PR TITLE
block validate height

### LINKED ISSUE #4090: sync break when Node evil
when injectNulls=-1   Node evil

Normal node
lotus chain list
0: (Sep 29 15:26:26) [ bafy2bzacec6zka46q3fheob4o653qssv5oj7b752w53qlqlgjgn4wrgogu4em: t00, ]
1: (Sep 29 15:26:30) [ bafy2bzacecgnt67z3ysfnlxop7lzcw2esyooeupw2zycyzyb3dtanhouzcq24: t01000, ]
2: (Sep 29 15:26:34) [ bafy2bzaceacr4txs3id5sypyrvkl6bqadv2x7hulbhgl2hbehkcsoypoys5si: t01000, ]
3: (Sep 29 15:26:38) [ bafy2bzacedl7gvg6xmjxsnf3nxayfzkny4l5zdxgmidtp5walru3tvhu74wei: t01000, ]
4: (Sep 29 15:26:42) [ bafy2bzacebecdfpwusao3hrvliuod2tm7wpufil6zl6hmgmmzbw4qc2kfbhja: t01000, ]
5: (Sep 29 15:26:46) [ bafy2bzacebll3bshvdgp4nw3tncauzj4xromwx7nwbw2fpgspdbumlo7tguiu: t01000, ]
6: (Sep 29 15:26:50) [ bafy2bzacedlmsicysy42l4otvjezsgpnvwz3nrh5ahf5w5t6hu34cwbq3yvrs: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzacedc6mpml3ggykfevwmbilzo6aiizle2jqbi3dtjcxe65n7uodjjxc: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzacebgwkj4izaa3nenjruafy56icnjeo46v47uop7e5uf75njukavnic: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced6owft5drj2ny7fazbhoedzjkjkapdjwugrko5lcs3ef5ju52cny: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced5m5quovypbp5z4a4wdnsifinovipfan7pm6awvmumjqvetn5kwe: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaceawt2wbpgq5ib6svuhxoxbl6hhlwt32lvrrnxjytegjxwxpc7cs4u: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced7h6dabtop5udrpuhhcwcwknugbwyhba636yazvm7bfjoho4dxuo: t01000, ]
7: (Sep 29 15:26:54) [ bafy2bzaced7krxxy7namyyj4aamllq4jmopoycjs2chbextstiylvtju7pq5g: t01000, ]
https://github.com/filecoin-project/lotus/blob/14791420478a14bd7181af2d590697fd7968e135/chain/sync.go#L737-L740

### PR DESCRIPTION
**Pull request by zgfzgf**
fix #4090 
Node evil
lotus chain list
... ...
7: (Sep 29 15:26:54) [ bafy2bzaceaphw3y7mv557lhpf2k3wmmbnfvr52r7zsc2qogitokfafpxq6jnw: t01000, ]
8: (Sep 29 15:26:58) [ bafy2bzaced577iipshzvvwpyn2kmpaqo3jrjxrkfauylq7wavhrqpkwdnu5e4: t01000, ]
9: (Sep 29 15:27:02) [ bafy2bzacecvw64pu527dh7554chhid2bmklffefvxu77dklt4aafgdghwm45i: t01000, ]
10: (Sep 29 15:27:06) [ bafy2bzacebscylcsnsecx7ct2ivzr6wkzd732o6tmdmukmtyf6xb7ewlxy63k: t01000, ]
10: (Sep 29 15:27:06) [ bafy2bzacebyt52vq3nqoo4pbd2xovdwutojqtthqtefbwemmmezbm4csvjlhk: t01000, ]
10: (Sep 29 15:27:06) [ bafy2bzacecgf3sfhjylbe7jp6n47jes7xb67clpeuj6im5rfevg6szsl2vkni: t01000, ]

Normal node
lotus chain list
... ...
7: (Sep 29 15:26:54) [ bafy2bzaceaphw3y7mv557lhpf2k3wmmbnfvr52r7zsc2qogitokfafpxq6jnw: t01000, ]
8: (Sep 29 15:26:58) [ bafy2bzaced577iipshzvvwpyn2kmpaqo3jrjxrkfauylq7wavhrqpkwdnu5e4: t01000, ]
9: (Sep 29 15:27:02) [ bafy2bzacecvw64pu527dh7554chhid2bmklffefvxu77dklt4aafgdghwm45i: t01000, ]
10: (Sep 29 15:27:06) [ bafy2bzacebscylcsnsecx7ct2ivzr6wkzd732o6tmdmukmtyf6xb7ewlxy63k: t01000, ]

### CODE REVIEW

**Comment by schomatis** [comment]
Hey @zgfzgf, thanks for submitting this. Could you add a test case that triggers this please? Or explain what would be the code flow that leads to this case?

We normally check that the incoming blocks are in decreasing order when fetching the chain so one block always has a higher height than its parent. If we were to receive a block with a lower height that the heaviest one we have then that would mean a possible fork that would trigger a different logic (`syncFork`).

**Comment by schomatis** [comment]
Also, the `injectNulls` case you mention in https://github.com/filecoin-project/lotus/issues/4090 is a problem only for the same miner that generates that block since we (as a special case) bypass all the logic above mentioned (which an external node would not bypass, rejecting the incoming block).

https://github.com/filecoin-project/lotus/blob/e4e3a0362f59596d67c8dd83fb574a9d37090a13/chain/sync.go#L241

**Comment by zgfzgf** [comment]
When I was learning mining synchronization code, I found no place to verify block height information
The other blockchain projects are auto added 1

So I changed some of the code (keeping the height unchanged) as an attack node

Attack nodes can synchronize blocks to normal nodes. 
As the example above, I have done experiments again just now, or as above

**The normal node is compiled by GitHub source code
The attack node is compiled by the modified code**

Therefore, it is better to increase block height verification, and at the same time, it is better to increase the judgment of height in mining code. Now, it mainly verifies weight

**Comment by zgfzgf** [comment]
hello @schomatis 
The attack node can be implemented without changing a lot of code. I changed it locally a week ago, but I didn't save it. Now I only keep the executable program

If you don't quite understand what I mean, I'll submit the modified code to implement the attack node

**Comment by zgfzgf** [comment]
https://github.com/zgfzgf/lotus/tree/height-unchanged
@schomatis 
Test steps:

As shown above
1. The first 10 blocks of attacking nodes run with normal node program
2. Then close the program
3. The attack node uses the above code compiler to run

Of course, there are other attack programs

**Comment by schomatis** [comment]
Hey @zgfzgf, thanks for the information. I understand and agree with what you're saying, what I was trying to say in https://github.com/filecoin-project/lotus/pull/4091#issuecomment-704433124 is that I think that change only affects the miner who generated the fake block, other nodes will verify the height difference and reject it. If you have observed otherwise please let me know.

**Comment by schomatis** [comment]
As a demonstration of what I'm saying, try to rebase your commit https://github.com/zgfzgf/lotus/commit/3f1cfa0faa8b1c1fefd24a36b6fc41b6eef12e5e on top of https://github.com/filecoin-project/lotus/pull/4192 (which removes the bypass of the checks for the miner that produces the block) to see if you can reproduce the error.

**Comment by zgfzgf** [comment]
@schomatis 
NOT  ”other nodes will verify the height difference and reject it“

The normal node accept it
see #4090

**Comment by zgfzgf** [comment]
other nodes accept it

**Comment by zgfzgf** [comment]
https://github.com/filecoin-project/lotus/blob/8f35a5c03693623ade671e447af8badee208dd8c/chain/sync.go#L1385-L1388
Node Online
Block by block synchronization
repeat the test

**Review by arajasek — APPROVED** [review]
Would prefer the check phrased as `if h.Height <= baseTs.Height...`, but this LGTM.

**Pull request closed without merging**
