### PR TITLE
fix fil to be pretty print

### LINKED ISSUE #289: FIL values should be pretty printed
I suggest the following:
  - `X attoFIL` if `val < 0.01μFIL`
  - `X μFIL` if `val < 0.1mFIL`
  - `X mFIL` if `val < 0.1 FIL`
  - otherwise `X FIL`

All prints should use thousands separator `,`, and be printed with at least 6 fractional digits.
It should be done on CLI side, with a possible override to always use `attFIL`.

### PR DESCRIPTION
**Pull request by deaswang**
fix #289 
Is this format fine?

### CODE REVIEW

**Comment by whyrusleeping** [comment]
I'm not entirely sure i want to get into using suffixes, they can just end up being confusing to the user. Especially because it can be hard to immediately tell the difference between different suffixes.

Thoughts @magik6k @Kubuxu ?

**Comment by Kubuxu** [comment]
I had a more simplified idea: https://github.com/filecoin-project/lotus/issues/289
It reduces number of prefixes that users need to know.

We also have to handle prefixes we output in `ParseFIL`.

**Comment by Kubuxu** [comment]
@whyrusleeping that is why I wanted to limit us to mili, micro and atto. Which are used in Bitcoin regularly (the atto is called satoshi).

**Comment by deaswang** [comment]
@whyrusleeping @Kubuxu Then how to fix this? how about use two format: one use FIL with full fractional digits for normal user, one use metric prefix for professional user. 
and the bug need to fix when value is 1000 FIL, `strings.TrimRight(strings.TrimRight(r.FloatString(18), "0"), ".")` return 1 FIL. how about use "%g" as output format.

**Comment by whyrusleeping** [comment]
I believe the issue here has been resolved

**Pull request closed without merging**
