### PR TITLE
correct int/uint types for GetRandomness function

### PR DESCRIPTION
**Pull request by steven004**
This is just as #616 , but resubmit based on the the current master code due to too much change happened.

### CODE REVIEW

**Comment by steven004** [comment]
Do the codecov check failures have to be fixed before merge? I did not really see where the failures come from. :-)

**Comment by Kubuxu** [comment]
Nah, the codecov failures are there to remind us to write more tests.

**Comment by whyrusleeping** [comment]
I think that this is no longer necessary, the relevant functions have been changed, and I think normalized to solve the issue presented here. Thoughts @steven004 ?

**Comment by steven004** [comment]
yes. I am closing this.

**Pull request closed without merging**
