### PR TITLE
Randomness: Move getters from ChainAPI to StateAPI

### PR DESCRIPTION
**Pull request by arajasek**
These arguably always belonged here, but especially so now that we versioned behaviour

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
Should bump the v1 fullnode api version

**Comment by arajasek** [comment]
> Should bump the v1 fullnode api version

Yessir, done

**Comment by magik6k** [comment]
The paych test fail looks concerning:
```
2021-09-13T15:43:54.528Z	ERROR	storageminer	storage/wdpost_run.go:874	estimating gas	{"error": "estimating gas used: message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16)", "errorVerbose": "estimating gas used:\n    github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas\n        /home/circleci/project/node/impl/full/gas.go:329\n  - message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16):\n    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit\n        /home/circleci/project/node/impl/full/gas.go:295"}
2021-09-13T15:43:54.529Z	WARN	vm	vm/runtime.go:350	Abortf: post commit randomness mismatched
2021-09-13T15:43:54.529Z	WARN	vm	vm/runtime.go:149	VM.Call failure in call from: f0102 to f01000: post commit randomness mismatched (RetCode=16):
    github.com/filecoin-project/specs-actors/v5/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1
        /go/pkg/mod/github.com/filecoin-project/specs-actors/v5@v5.0.4/actors/builtin/miner/miner_actor.go:409
2021-09-13T15:43:54.529Z	WARN	vm	vm/vm.go:537	Send actor error	{"from": "f0102", "to": "f01000", "nonce": 1, "method": "5", "height": "684", "error": "post commit randomness mismatched (RetCode=16):\n    github.com/filecoin-project/specs-actors/v5/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1\n        /go/pkg/mod/github.com/filecoin-project/specs-actors/v5@v5.0.4/actors/builtin/miner/miner_actor.go:409"}
2021-09-13T15:43:54.529Z	ERROR	storageminer	storage/wdpost_run.go:186	submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPoStMessage
        /home/circleci/project/storage/wdpost_run.go:836
  - GasEstimateMessageGas error:
    github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
        /home/circleci/project/node/impl/full/mpool.go:160
  - estimating gas used:
    github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas
        /home/circleci/project/node/impl/full/gas.go:329
  - message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16):
    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
        /home/circleci/project/node/impl/full/gas.go:295
```

**Comment by arajasek** [comment]
> The paych test fail looks concerning:
> 
> ```
> 2021-09-13T15:43:54.528Z	ERROR	storageminer	storage/wdpost_run.go:874	estimating gas	{"error": "estimating gas used: message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16)", "errorVerbose": "estimating gas used:\n    github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas\n        /home/circleci/project/node/impl/full/gas.go:329\n  - message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16):\n    github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit\n        /home/circleci/project/node/impl/full/gas.go:295"}
> 2021-09-13T15:43:54.529Z	WARN	vm	vm/runtime.go:350	Abortf: post commit randomness mismatched
> 2021-09-13T15:43:54.529Z	WARN	vm	vm/runtime.go:149	VM.Call failure in call from: f0102 to f01000: post commit randomness mismatched (RetCode=16):
>     github.com/filecoin-project/specs-actors/v5/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1
>         /go/pkg/mod/github.com/filecoin-project/specs-actors/v5@v5.0.4/actors/builtin/miner/miner_actor.go:409
> 2021-09-13T15:43:54.529Z	WARN	vm	vm/vm.go:537	Send actor error	{"from": "f0102", "to": "f01000", "nonce": 1, "method": "5", "height": "684", "error": "post commit randomness mismatched (RetCode=16):\n    github.com/filecoin-project/specs-actors/v5/actors/builtin/miner.Actor.SubmitWindowedPoSt.func1\n        /go/pkg/mod/github.com/filecoin-project/specs-actors/v5@v5.0.4/actors/builtin/miner/miner_actor.go:409"}
> 2021-09-13T15:43:54.529Z	ERROR	storageminer	storage/wdpost_run.go:186	submit window post failed: pushing message to mpool:
>     github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPoStMessage
>         /home/circleci/project/storage/wdpost_run.go:836
>   - GasEstimateMessageGas error:
>     github.com/filecoin-project/lotus/node/impl/full.(*MpoolAPI).MpoolPushMessage
>         /home/circleci/project/node/impl/full/mpool.go:160
>   - estimating gas used:
>     github.com/filecoin-project/lotus/node/impl/full.(*GasModule).GasEstimateMessageGas
>         /home/circleci/project/node/impl/full/gas.go:329
>   - message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16):
>     github.com/filecoin-project/lotus/node/impl/full.gasEstimateGasLimit
>         /home/circleci/project/node/impl/full/gas.go:295
> ```

should be fixed

**Review by magik6k — APPROVED** [review]

**Pull request merged**
