### PR TITLE
add send from != to

### LINKED ISSUE #4969: lotus send from == to problem
aa73d1603b665244c7d6d689965908d

### PR DESCRIPTION
**Pull request by zgfzgf**
fix #4969

### CODE REVIEW

**Comment by jennijuju** [comment]
There is nothing wrong for a sender do a self transfer if they want to IMO.

**Comment by zgfzgf** [comment]
It is meaningless to transfer money to oneself,
which wastes gas charge and network resources

**Comment by magik6k** [comment]
Self-transfers aren't invalid, and can be useful when you need to put bits of data on-chain for whatever reason (web3 apps, smart-contract integration in other blockchains, proving address ownership, etc..)

**Comment by zgfzgf** [comment]
lotus send is may not
others are OK

**Pull request closed without merging**
