### PR TITLE
feat: sync: harden chain sync

### PR DESCRIPTION
**Pull request by Stebalien**
## Proposed Changes

This makes two changes:

1. Write headers in chain order, not reverse order. This shouldn't matter, but it may help if badger crashes.
2. Force `collectChain` to collect the correct chain. This shouldn't matter, but we might as well (as long as it's safe).

WRT 1, I'm worried about the following:

1. Attempt to sync a chain from epochs 3-7.
2. Write tipsets 7, 6, 5.
3. Badger realizes that the current vlog is "full", so it creates a new one.
4. Write tipsets 4, 3.

My concern is that, while badger will write _synchronously_, it doesn't call `fsync `on the file itself, and the directory containing the file. That means, if the machine crashes, the new vlog might just disappear.

Of course, the _right_ solution would be to fix badger to sync the file/directory metadata, but that's not likely to happen, ever.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [x] Tests exist for new functionality or change in behavior
- [x] CI is green

### CODE REVIEW

**Review by arajasek — COMMENTED** [review]
@Stebalien I think the 2 changes you describe in the PR description make sense and are good to go. I don't understand why we're no longer putting the `maybeHead`, though.

**Comment by Stebalien** [comment]
> I don't understand why we're no longer putting the maybeHead, though.

We should already be doing that here:

https://github.com/filecoin-project/lotus/blob/3f03e63fd1bcebc37fc582bf84d86808fcb6f850/chain/sync.go#L1191-L1198

We check that `headers[0]` is the correct head here: https://github.com/filecoin-project/lotus/blob/3f03e63fd1bcebc37fc582bf84d86808fcb6f850/chain/sync.go#L1184-L1186.

**Comment by arajasek** [comment]
@Stebalien I do not think you're right here -- this is `PutTipset`ting, which is tremendously unfortunately named, but is what actually:

- expands tipsets where possible
- actually updates the chain head (if necessary).

I think dropping that code will break everything, though I'm admittedly not 100% sure.

**Comment by Stebalien** [comment]
Oh! Yes, you're right. I saw `P...TipSet` and didn't even register that they were different functions.

**Review by arajasek — APPROVED** [review]

**Pull request merged**
