### PR TITLE
Staging branch for Network Version 16

### PR DESCRIPTION
**Pull request by vyzo**
Staging branch for all things NV16.

## TODO

- [x] https://github.com/filecoin-project/lotus/pull/8429
- [x] Execution traces

## Follow ups from #8429
- [x] filecoin-ffi update
- [x] fix the bundles situation for devnets, caterpillar, etc.
- [ ] set the upgrade epoch for Caterpillarnet
- [ ] make itests green.

### CODE REVIEW

**Comment by jennijuju** [comment]
I dont think we want 3c8aa18f70d54edbef778659485da8c4bd7af2a9 in master

**Comment by vyzo** [comment]
sure, we can always drop it.

**Comment by simlecode** [comment]
My project references Lotus, but I'm having problems compiling.
error info: go/pkg/mod/github.com/filecoin-project/lotus@v1.15.2-0.20220419220549-b60d795a5dec/build/builtin_actors_mainnet.go:17:12: pattern builtin-actors/v7/builtin-actors-mainnet.car: no matching files found

**Comment by vyzo** [comment]
you need to make first so that the appropriate bundles are fetched.

**Comment by vyzo** [comment]
you can also manually run fetch-bundles.sh

**Comment by simlecode** [comment]
I understand what you're saying, but What I mean is that A depends on Lotus, and A failed to compile.
A --> Lotus
Compiling Lotus only is good.

**Comment by simlecode** [comment]
I understand what you're saying, but What I mean is that A depends on Lotus, and A failed to compile.
A --> Lotus
Compiling Lotus only is good.

**Pull request closed without merging**
