### PR TITLE
feat: extend datacap expiration

### PR DESCRIPTION
**Pull request by swift-mx**
## Related Issues
This is Droplet extend datacap expiration function https://github.com/ipfs-force-community/droplet/blob/a9bceef4afcd3141ee929e72483ba2f812069c02/cmd/droplet-client/datacap.go#L35

### CODE REVIEW

**Review by LexLuthr — CHANGES_REQUESTED** [review]
@swift-mx Can we please increase the scope of this PR to cover all cases of the claim extension?
1. Extend all claims for a miner ID
2. Extend all claims for multiple miner IDs
3. Extend specified claims for a miner ID
4. Extend specific claims for specific miner ID

1. In case, wallet address is different from claim.Client then we should filter out such claims and in the end ask client if they wish to extend such claims as well. Extending such claims require client to send an allocation message and client will end up spending the data cap. This could be a prompt with all the info and final data cap requirements asking client to choose between "Yes" or "No". You can also add a `--force` flag to skip this check.

TermMax should default to `verifregtypes.MaximumVerifiedAllocationTerm` if not provided by the user.

**Comment by LexLuthr** [comment]
Please note that we have one more PR to implement claim extension https://github.com/filecoin-project/lotus/pull/11545

I would request you and @nicelove666 to work together to avoid duplicating efforts and expanding the scope of the command as requested.

**Comment by beck-8** [comment]
https://github.com/filecoin-project/lotus/issues/10001

**Comment by LexLuthr** [comment]
Closing this there has been no input from author. https://github.com/filecoin-project/lotus/pull/11711 supersedes this now.

**Pull request closed without merging**
