### PR TITLE
Splitstore: add retention policy option for keeping messages in the hotstore

### PR DESCRIPTION
**Pull request by vyzo**
It appears that deals have a longish lookback for messages; this adds an option to accommodate them.

cc @ribasushi

### CODE REVIEW

**Comment by vyzo** [comment]
Actually, it's utility goes beyond lookbacks -- it allows nodes running with discard + the retention policy to support other nodes syncing from them, even if they fall behind -- up to the retention interval.

So running a booster/bootstrapper with discard and some 30 finalities retention is a very reasonable proposition.
cc @travisperson

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
A test would be nice.

**Comment by vyzo** [comment]
indeed, i'll add one.

**Comment by magik6k** [comment]
Issue for testing: https://github.com/filecoin-project/lotus/issues/6834

**Review by Kubuxu — APPROVED** [review]

**Review by magik6k — APPROVED** [review]

**Pull request merged**
