### PR TITLE
chore: deps: update FFI, FVM, and actors

### PR DESCRIPTION
**Pull request by rjan90**
## Related Issues
Towards nv22/lotus v1.26.0-rc1 release

## Proposed Changes

Updates:
- FVM to 4.1.2
- FFI to [v1.26.0-rc2](https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.26.0-rc2)
- [Builtin-actors v13.0.0-rc.2](https://github.com/filecoin-project/builtin-actors/releases/tag/v13.0.0-rc.2)

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
I have a branche (https://github.com/filecoin-project/lotus/tree/steb/update-fvm) that updates the FVM and addresses the breaking changes to the tracing API. That branch is currently based on master, but should I move it to feat/nv22?

**Comment by rjan90** [comment]
> I have a branch (https://github.com/filecoin-project/lotus/tree/steb/update-fvm) that updates the FVM and addresses the breaking changes to the tracing API. That branch is currently based on master, but should I move it to feat/nv22?

Yeah, that would be ideal. Once `feat/nv22` branch is more complete we will merge it back to master #11600.

**Comment by Stebalien** [comment]
Hm. That's not ideal as I want to make PRs that depend on these changes, and these PRs are not a part of nv22. I didn't realize the diff was _that_ big.

Is there any reason not to make the PR against master then back merge? Do we not do back-merging to integration branches?

**Comment by aarshkshah1992** [comment]
@rjan90 PR looks good to me but we will need @Stebalien's changes from [here](https://github.com/filecoin-project/lotus/tree/steb/update-fvm) before CI can be green.

**Review by aarshkshah1992 — APPROVED** [review]

**Review by rvagg — APPROVED** [review]
If I cherry-pick this in to `feat/built-in-actor-events-api` which requires the actor events work, and I add in #11611, and I run against https://github.com/filecoin-project/go-state-types/pull/236 then it's all 👍. And I even get the right `"balance"` encoded form out of events which was that thing I fixed in actors yesterday:

```
Event<height=772, msg=bafy2bzacebadnt32yvrwugww64tymuv4zdpwl26hnv5et6js5oxxj3sokjjnq, emitter=f06, reverted=false, $type="verifier-balance", verifier=100, balance={"/":{"bytes":"ABdIdsDw"}}>
```

**Comment by rvagg** [comment]
Pulled in the v13.0.0-rc.2 commit to #11611 where, by the powers of both branches combined, we get 💚 . Merged that one in to feat/nv22 so we're all good now.

**Pull request closed without merging**
