### PR TITLE
Add --all-sectors flag in lotus-miner sectors extend

### PR DESCRIPTION
**Pull request by chadwick2143**
Renews all(except v1) sectors expiration

### CODE REVIEW

**Comment by magik6k** [comment]
(gen-check can be fixed with `make docsgen-cli`)

**Comment by chadwick2143** [comment]
> (gen-check can be fixed with `make docsgen-cli`)

fixed
thanks

**Comment by chadwick2143** [comment]
I'm extending sectors using `lotus-miner sectors extend --all-sectors --new-expiration 1856880` for tens of miners, but only one failed.

Firstly, I got a error: `ERROR: mpool push message: mpool push: failed to push message: message not valid for block inclusion: 'GasLimit' field cannot be greater than a block's gas limit`

Then I tried again, this time I got a message CID `bafy2bzacecjcfyfh7hcvka2ly5c73jwbfo34qurmcf45pojsxxdqkrlcbpnue` and a error: `ERROR: mpool push message: mpool push: failed to push message: message not valid for block inclusion: 'GasLimit' field cannot be greater than a block's gas limit`

Now the [message](https://filfox.info/en/message/bafy2bzacecjcfyfh7hcvka2ly5c73jwbfo34qurmcf45pojsxxdqkrlcbpnue) is on chain but it seems that no sectors was extended. Because I still get this after do `lotus-miner sectors check-expire --cutoff 518400 | head`
```
ID      SealProof  InitialPledge  Activation                         Expiration                        MaxExpiration                  MaxExtendNow
79297   8          171.759 mFIL   1049154 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305154 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
79547   8          171.758 mFIL   1049161 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305161 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
79689   8          171.755 mFIL   1049183 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305183 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
80003   8          171.755 mFIL   1049183 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305183 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
80072   8          171.732 mFIL   1049440 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305440 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
80252   8          171.749 mFIL   1049260 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305260 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
80377   8          171.758 mFIL   1049161 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305161 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
81605   8          171.757 mFIL   1049169 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305169 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
82464   8          171.753 mFIL   1049218 (14 weeks 6 days ago)      1654763 (in 15 weeks 8 hours)     6305218 (in 4 years 37 weeks)  2906580 (in 1 year 25 weeks)
```
Could you please help me with this? Is this because there are too many sectors to extend? @magik6k

**Comment by chadwick2143** [comment]
> I'm extending sectors using `lotus-miner sectors extend --all-sectors --new-expiration 1856880` for tens of miners, but only one failed.
> 
> Always get this error: `ERROR: mpool push message: mpool push: failed to push message: message not valid for block inclusion: 'GasLimit' field cannot be greater than a block's gas limit`
> 
> I guess this is because there are too many sectors to extend.

This has been fixed after a little change:
```
-                                       if scount > addressedMax || len(p.Extensions) == declMax {
+                                       if scount > addressedMax*3/4 || len(p.Extensions) == declMax {
```

Tried `addressedMax*4/5` firstly but still get same error.
Maybe 25000 is too large for `miner.AddressedSectorsMax`?

**Comment by chadwick2143** [comment]
PTAL @magik6k @arajasek

**Comment by ZenGround0** [comment]
Hey @chadwick2143 is this one no longer needed like #7741 or should I give it a review?

**Pull request closed without merging**
