### PR TITLE
Reintroduce use all gas on fail

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by arajasek** [comment]
FYI, this was taken out a few months ago because go-filecoin only charges for actual gas used (even in failure cases), and we decided that was correct and that Lotus needed to change.

**Comment by Kubuxu** [comment]
Is ther any note of that discussion?

**Comment by arajasek** [comment]
To be clear, I think this is good and we should merge it.

> Is ther any note of that discussion?

No, it happened on Slack (probably gone by now), but the conversation was basically "That's not what the spec says, that's not what gfc does, therefore Lotus is wrong and should be changed".

There's also this, but no references to it: https://github.com/filecoin-project/specs/issues/502.

**Comment by magik6k** [comment]
So technically https://github.com/filecoin-project/lotus/pull/2764 should achieve a similar thing (at least for messages which fail early), and with slightly better miner incentives

**Pull request closed without merging**
