### PR TITLE
Increase client polling interval

### PR DESCRIPTION
**Pull request by aarshkshah1992**
For https://github.com/filecoin-project/go-fil-markets/issues/503.

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
Seems to make tests really upset

**Comment by arajasek** [comment]
@aarshkshah1992 @dirkmc Any investigation into why this made tests really upset?

**Comment by jennijuju** [comment]
@aarshkshah1992 @dirkmc please move from draft to open for review once the tests are fixed

**Comment by raulk** [comment]
@aarshkshah1992 is this still desired?

**Pull request closed without merging**
