### PR TITLE
chore: fix some comments for struct field

### PR DESCRIPTION
**Pull request by linghuying**
## Proposed Changes

 fix some comments for struct field

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] Update CHANGELOG.md or signal that this change does not need it.
  - If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
  - If the change does not require a CHANGELOG.md entry, do one of the following:
    - Add `[skip changelog]` to the PR title
    - Add the label `skip/changelog` to the PR
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by rvagg** [comment]
@linghuying thanks, you'll need to `make gen` and check in the changes from this please

**Comment by linghuying** [comment]
> s, you'll need to `make gen` and check in the changes from this please

Sorry. I get an error message:

`chain/consensus/utils.go:12:2: github.com/filecoin-project/filecoin-ffi@v1.28.0-rc2 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /Users/sc/github/linghuying-github/lotus/extern/filecoin-ffi/go.mod: no such file or directory
chain/vm/fvm.go:21:2: github.com/filecoin-project/filecoin-ffi@v1.28.0-rc2 (replaced by ./extern/filecoin-ffi): reading extern/filecoin-ffi/go.mod: open /Users/sc/github/linghuying-github/lotus/extern/filecoin-ffi/go.mod: no such file or directory
make: *** [type-gen] Error 1`

**Comment by rvagg** [comment]
@linghuying `make deps` to get that set up

**Comment by rvagg** [comment]
Sorry @linghuying, it's a bit more complicated if you've not done it for the first time. See https://lotus.filecoin.io/lotus/install/prerequisites/#supported-platforms and click on your OS at the bottom and it'll show you some basic install instructions for a few dependencies, like `pkg-config`.

**Comment by rvagg** [comment]
completed via https://github.com/filecoin-project/lotus/pull/12376

**Pull request closed without merging**
