### PR TITLE
release: v1.26.2

### PR DESCRIPTION
**Pull request by rjan90**
## Proposed Changes
Prep for the v1.26.2 patch release - Which will include the PR that ensures the builtin actor event entries are ordered by insertion order when selected ([#11834](https://github.com/filecoin-project/lotus/pull/11834)) + some Lotus-Miner patch fixes.

- Make gen & Make docsgen-cli
- Update changelog
- Cherry-pick PRs:
   - https://github.com/filecoin-project/lotus/pull/11831
   - https://github.com/filecoin-project/lotus/pull/11832
   - https://github.com/filecoin-project/lotus/pull/11839 (only the 9e51a0eece17d4af8230b508d8a6b04eaf4183b5 commit) 
   - https://github.com/filecoin-project/lotus/pull/11819

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
Mind if we sneak https://github.com/filecoin-project/lotus/pull/11844 in as well?

**Comment by jennijuju** [comment]
> Mind if we sneak #11844 in as well?

Doesn’t seems like to be needed for nv22 - we will have another feature release train kick off next Thursday, let’s wait and having this PR go through the regular release process instead of fast tracking it.

**Review by rvagg — APPROVED** [review]
https://github.com/filecoin-project/lotus/compare/release/v1.26.1...prep-release-v1262 is the full diff from 1.26.1 for anyone else wanting to see the whole thing

**Comment by rvagg** [comment]
included in #11849

**Pull request closed without merging**
