### PR TITLE
Add Rustup installation instructions for Ubuntu

### PR DESCRIPTION
**Pull request by jimpick**
Also made a note about `make clean` failing on first try.

### CODE REVIEW

**Comment by travisperson** [comment]
Do we now have a rust dependency in lotus?

**Comment by whyrusleeping** [comment]
You shouldnt need rust to build lotus, but its nice to have around if you are building things from really scratch. Maybe this could go in an 'optional dependencies' section?

**Comment by jimpick** [comment]
I'm going to spin up an Ubuntu EC2 machine to confirm that rust isn't needed.

**Comment by jimpick** [comment]
Confirmed, rust isn't needed. I'll close this ... I'd probably leave "optional dependencies" for the installation instructions for developers.

**Pull request closed without merging**
