### PR TITLE
Updating import docs with full path to file, may close #441

### LINKED ISSUE #441: lotus client import ./hello.txt failed
## Description
`lotus client import ./file` fails in other folders but succeed in `lotus` located folder.  

## Reproduce
```
$ echo "This is an import issue" > hello.txt
$ pwd
/Users/Steven/temp
$ lotus client import ./hello.txt
2019-10-22T16:58:56.443+0800	WARN	main	lotus/main.go:67	open hello.txt: no such file or directory
$ mv hello.txt ~/go/bin 
$ cd ~/go/bin
$  lotus client import ./hello.txt
bafkreiesifpf5qe53vm65ofyaak74atyru63q4mdeojrgmdyywrixk44ui
```

### PR DESCRIPTION
**Pull request by eshon**

### CODE REVIEW

**Comment by magik6k** [comment]
We should just expand the path in the CLI command

**Comment by eshon** [comment]
> We should just expand the path in the CLI command

How about just $PWD?

**Comment by Kubuxu** [comment]
In short, yes adding `$PWD` to it in the lotus cli. As in: before the path gets passed to the daemon call https://golang.org/pkg/path/filepath/#Abs on it.

**Comment by whyrusleeping** [comment]
I think after #462 this is no longer an issue

**Pull request closed without merging**
