### PR TITLE
feat: infra/ci: add `lotus-test` image as CI build step

### PR DESCRIPTION
**Pull request by nonsense**
This PR is:
1. Adding a `lotus-test` Docker target to `Dockerfile.lotus`
2. Build step to produce `lotus-test` image on commit to `master`.

We need this, because we are using the `--tags=debug` lotus binaries as part of the integration tests for Boost -- https://github.com/filecoin-project/boost/blob/main/.circleci/config.yml#L67

Ideally these images should be produced by `filecoin-project/lotus` build system.

---

TODO:
- [x] create public ECR repository for `lotus-test`, same as `lotus-dev`.

### CODE REVIEW

**Comment by nonsense** [comment]
@travisperson provided this PR is accepted, could you help create the repository on the AWS account?

This will address the failure on `build-and-push-image-2`.

**Review by dirkmc — APPROVED** [review]

**Comment by jennijuju** [comment]
Please update the title according to the PR template! https://github.com/filecoin-project/lotus/blob/d9c763437e47186d81e01e4451c843ee95c59e33/.github/pull_request_template.md?plain=1#L15

**Comment by nonsense** [comment]
@magik6k @travisperson any chance we can push this forward? It will be handy if we have up-to-date docker images for dependent projects, such as Boost.

**Comment by travisperson** [comment]
Yes, I will create the `lotus-test` repo

**Review by magik6k — APPROVED** [review]

**Pull request merged**
