### PR TITLE
add command to print state size statistics of actors

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by lanzafame** [comment]
@whyrusleeping how expensive is this command and would you want this to be graphed?

**Comment by whyrusleeping** [comment]
@lanzafame it takes about 5 seconds to run on my computer, we could probably parallelise it and make it go faster. Alternatively, we can just run it for a specific set of actors, and its pretty fast that way

**Comment by lanzafame** [comment]
@whyrusleeping is the set of actors unbounded?

**Comment by whyrusleeping** [comment]
@lanzafame yeah, its all the actors in the system

**Comment by lanzafame** [comment]
ok cool, means it is fine to expose to prometheus.

**Pull request merged**
