### PR TITLE
feat: test: Add more post-migration sanity checks

### PR DESCRIPTION
**Pull request by arajasek**
## Related Issues

This builds on #11149 to add a few more "vanilla" sanity checks that always apply

## Proposed Changes

Check that:

- system actor is now v12
- the Manifest stored in the system actor state matches what Lotus expects

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by snissn** [comment]
looks great!

**Review by snissn — DISMISSED** [review]
:+1:

**Comment by snissn** [comment]
Hi! I had approved this pr conditional on the checks passsing, and unfortuantely there's some style checks that are failing here

**Comment by arajasek** [comment]
Merging, test is failing on base branch too.

**Pull request merged**
