### PR TITLE
fix: add check manual-stateless-deal with interactive deal making

### PR DESCRIPTION
**Pull request by emf-developer**
add check manual-stateless-deal with interactive deal making as --manual-stateless-deal can not be combined with interactive deal mode.

### CODE REVIEW

**Comment by emad22552** [comment]
@jennijuju @ribasushi

**Comment by magik6k** [comment]
> Can / Should I do something to pass these failed tests?

Yes, run `go fmt ./...`, then commit changes

**Comment by emad22552** [comment]
@magik6k @jennijuju @ribasushi

**Review by magik6k — APPROVED** [review]

**Comment by silvianetobessa** [comment]
Hello @EmadMF!

This contribution to the Filecoin codebase was voted as impactful during Q1 and is eligible for a FIL prize as part of a Protocol Labs experiment to reward open source contributions from the community (see[ full details here](https://filecoin.io/blog/posts/a-public-goods-experiment-on-filecoin-retroactively-funding-impact-with-quadratic-voting/)).

Please reach out to us through commons@protocol.ai to receive the instructions on how to claim your reward!

**Pull request merged**
