### PR TITLE
Delete TransferFunds Method

### PR DESCRIPTION
**Pull request by waynewyang**
fix method:VM.TransferFunds

### CODE REVIEW

**Comment by magik6k** [comment]
Wait, why does transferring funds work right now?

**Comment by Kubuxu** [comment]
That method is not used.

**Comment by waynewyang** [comment]
Yes, currently vm.Transfer(Function)  is used. but this PR also should be merged for safe.

**Comment by whyrusleeping** [comment]
@waynewyang could you actually just delete that method? Its not used, so its better we just drop it

**Comment by waynewyang** [comment]
@whyrusleeping  ok, but I think it better that using VM.TransferFunds method instead of vm.Transfer function, I'll update the PR if it's OK?

**Comment by whyrusleeping** [comment]
The `Transfer` method is the correct one, the `TransferFunds` method is no longer needed. Why do you think its better?

**Comment by waynewyang** [comment]
> The `Transfer` method is the correct one, the `TransferFunds` method is no longer needed. Why do you think its better?

I misunderstood something,  I thought perherps  that transfer will use the private variable in `VM`, I will delete the `TransferFunds` Method.

**Pull request merged**
