### PR TITLE
chainval | storage power actor tests

### PR DESCRIPTION
**Pull request by frrist**
adds minimal set of storage power actor tests, merge after #737

### CODE REVIEW

**Comment by frrist** [comment]
CI failing due to:
```
./lotus fetch-params --proving-params 1024
panic: error registering websocket protocol: protocol by the name "ws" already exists

goroutine 1 [running]:
github.com/libp2p/go-ws-transport.init.0()
	/go/pkg/mod/github.com/libp2p/go-ws-transport@v0.1.0/websocket.go:51 +0xe6

Exited with code exit status 2
```
perhaps a rebase is needed?

**Comment by whyrusleeping** [comment]
thats a really weird failure... cc @Kubuxu ?

**Comment by Kubuxu** [comment]
It is problem with libp2p dependencies/versions. They moved where `ws` protocol is defined so we need to make sure we use just one of these. (not sure which dependency it is).

**Comment by frrist** [comment]
Aborting as the the value of `PaymentChannelClosingDelay` as well as acceptable sector sizes has changed in lotus. This causes the tests here to fail. A new version of chain-validation will need to be created to address these.

**Pull request closed without merging**
