### PR TITLE
reasonable max value for initial sector expiration

### PR DESCRIPTION
**Pull request by zlhwdsz**

### CODE REVIEW

**Comment by jennijuju** [comment]
this is likely be fixed by another pr already, @magik6k will link it here and close this ticket or review this one.

**Comment by arajasek** [comment]
@jennijuju maybe https://github.com/filecoin-project/lotus/pull/6566?

**Comment by zlhwdsz** [comment]
Alright, then I just keep the max part.

**Review by Stebalien — APPROVED** [review]

**Comment by ZenGround0** [comment]
@zlhwdsz mind rebasing against master and merging?

**Comment by zlhwdsz** [comment]
@ZenGround0 Done.

**Pull request merged**
