### PR TITLE
add an api for removing multisig signers

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Review by Stebalien — COMMENTED** [review]
The remove changes make sense, but I'm missing context on the changes to MsigApprove.

**Review by magik6k — APPROVED** [review]

**Comment by whyrusleeping** [comment]
@Stebalien its fixing some really terrible UX.

**Comment by Stebalien** [comment]
But it's a _very_ late breaking change to a widely used (I assume?) API. I agree with the change in general, I just want to make sure you've thought about the fallout). We can always add an `ApproveWithoutTxnHash` function.

**Comment by whyrusleeping** [comment]
@Stebalien yep. Breaking the API on purpose. will be much harder the longer we wait.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Fair enough.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
