### PR TITLE
chore: update bitswap and some libp2p packages

### PR DESCRIPTION
**Pull request by Stebalien**
This removes some deprecated packages from the build tree.

### CODE REVIEW

**Comment by geoff-vball** [comment]
@Stebalien Reran them a few times and the unit tests do appear to actually be broken

**Comment by Stebalien** [comment]
@Jorropo there appears to be a significant regression in bitswap v0.10.1.

**Comment by Stebalien** [comment]
https://github.com/ipfs/go-bitswap/issues/584

**Comment by Jorropo** [comment]
I'm taking a look

**Comment by Jorropo** [comment]
@Stebalien this has been fixed in go-bitswap `v0.10.2`, I don't have perms to push on that branch, I'll let you bump it once more yourself.

**Review by arajasek — APPROVED** [review]

**Pull request merged**
