### PR TITLE
fix: eth json RPC: eth Filter IDs must act like ints with no leading 0x00 zeros

### PR DESCRIPTION
**Pull request by snissn**
## Related Issues
https://github.com/filecoin-project/lotus/issues/10170

## Proposed Changes
change serialization of ethFilterID type to remove leading zeros

## Additional Info
itests/eth_conformance_test.go was flaky failing some of the time and this should fix it

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by snissn** [comment]
This change is causing other tests to fail ie https://app.circleci.com/pipelines/github/filecoin-project/lotus/26527/workflows/d1125d69-1021-46d4-b554-4e6b0d75fe1f/jobs/837726

**Review by raulk — COMMENTED** [review]
I think this is more related to the "no leading zeros" requirement, i.e. "compact hex" encoding thing.

**Comment by iand** [comment]
Should subscriptionID be treated the same way?

**Comment by arajasek** [comment]
Closing this until we have a clear direction / get user feedback on the need. Test being tweaked in #10297

**Pull request closed without merging**
