### PR TITLE
feat: Instructions for setting up Grafana/Prometheus for monitoring local lotus node

### PR DESCRIPTION
**Pull request by fridrik01**
## Related Issues
https://github.com/filecoin-project/lotus/issues/10888

## Proposed Changes
This PR adds documentation for how to installation and setting up [`Prometheus`](https://prometheus.io/), [`Grafana`](https://grafana.com/) and [`node_exporter`](https://github.com/prometheus/node_exporter) to get a fully working monitoring system running against a local running lotus node. 

Currently the instructions have been tested on Mac M1 and Ubuntu linux.

This PR includes a pre-configured Prometheus configuration as well as an initial dashboard I created for investigating where time is spent in ApplyBlocks which is executed as part of ExecuteTipSet. We should aim to have dashboards targeted for each individual users (miners, rpc providers, core devs, etc) and maintain them inside the Lotus codebase (currently using `metrics/grafana` as the location for that). I leave that up to future PRs.

## Test plan

After following the installation readme, you should get something like (showing the default lotus metric dashboard):
image

And if you setup node_exporter, have rich dashboard for viewing your system metrics:
image

## Future work

Although the monitoring system described here should give good overview and analyzis, there are still a lot more things we can do to extend it with more capabilities (especially after we migrate to OpenTelemetry, see https://github.com/filecoin-project/lotus/issues/11268):

- Distributed tracing for critical codepaths
- Integration with [signoz](https://signoz.io/)
- Include logs in traces
- Alerting
- etc

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [x] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [x] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
This is really nice! 👏  I will open a issue in the Lotus-Docs as well, so that we can port this guide over there once it lands in a stable release!

**Comment by rjan90** [comment]
Suggested a couple of typo-fixes. The PR-heading could probably also be update to be in line with PR-checklist

**Comment by rjan90** [comment]
Just went through the tutorial on a Macbook M1 with a devnet, and 🚀
Screenshot 2023-09-20 at 16 31 19

**Comment by jennijuju** [comment]
This is awesome, thank you fridrcik!

**Review by rjan90 — APPROVED** [review]
LGTM!

**Review by arajasek — APPROVED** [review]
Working well on Arch Linux too!

**Pull request merged**
