### PR TITLE
Update mainnet.pi

### PR DESCRIPTION
**Pull request by cloudxin**
add venus node boostrap

## Related Issues

https://github.com/filecoin-project/venus/issues/6079
## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Fatman13** [comment]
CC @ognots 

As promised, Venus team has implemented bootstrap node related feature and uses a high availability node sponsored by [venushub](https://venushub.io/).

**Comment by ognots** [comment]
@Fatman13 this is amazing, thank you so much! we'll be sure to celebrate this contribution. I'm very excited to see the first interoperable bootstrap node, from an implementation outside Lotus.

**Review by ognots — APPROVED** [review]
I have ran the FIL-Infra bootstrap check script on this branch, and this bootstrap node is accessible from North America.

**Comment by Fatman13** [comment]
> I'm very excited to see the first interoperable bootstrap node, from an implementation outside Lotus.
🙏 🎉

> I have ran the FIL-Infra bootstrap check script on this branch, and this bootstrap node is accessible from North America.
The node is located in HK. Might be faster in Asia but should be able to handle connections across the global.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
