### PR TITLE
add rice box to required binaries

### LINKED ISSUE #6715: [BUG]  Remove go.rice completely from lotus
The use of go.rice was removed in https://github.com/filecoin-project/lotus/pull/6208 to support AppImage, but it was not completely removed and still exists in a few places that needs to be fixed.

```
➜  lotus git:(master) ag "github.com/GeertJohan/go.rice"
cmd/lotus-townhall/main.go
11:	rice "github.com/GeertJohan/go.rice"

cmd/lotus-fountain/main.go
12:	rice "github.com/GeertJohan/go.rice"

go.mod
9:	github.com/GeertJohan/go.rice v1.0.0

go.sum
39:github.com/GeertJohan/go.rice v1.0.0 h1:KkI6O9uMaQU3VEKaj01ulavtF7o1fWT7+pk/4voiMLQ=
40:github.com/GeertJohan/go.rice v1.0.0/go.mod h1:eH6gbSOAUv07dQuZVnBmoDP8mgsM1rtixis4Tib9if0=

testplans/lotus-soup/go.sum
43:github.com/GeertJohan/go.rice v1.0.0 h1:KkI6O9uMaQU3VEKaj01ulavtF7o1fWT7+pk/4voiMLQ=
44:github.com/GeertJohan/go.rice v1.0.0/go.mod h1:eH6gbSOAUv07dQuZVnBmoDP8mgsM1rtixis4Tib9if0=

build/tools.go
6:	_ "github.com/GeertJohan/go.rice/rice"
```

This is a fresh clone of lotus, I do not believe go.rice should show up anywhere in the source tree.

### PR DESCRIPTION
**Pull request by travisperson**
This is a temporary fix to resolve #6715 to ensure we do not break the devnet / testnet faucet on automated deployments.

### CODE REVIEW

**Comment by travisperson** [comment]
@jennijuju I'm going to be a temporary block on updating the faucet service during release deployments till this lands in an rc. Everything else will still work, just no changes the the faucet will automatically update which are infrequently anyways so no big issues I think.

**Comment by travisperson** [comment]
This isn't a complete fix. Townhall still depends on rice, but whatever folder it's using doesn't exist, and probably requires an additional build step to produce that is not being done in circle. This caused the build to fail.

**Comment by jennijuju** [comment]
Thanks @travisperson - what’s devnet faucet?

**Comment by travisperson** [comment]
Every network we setup has a facuet, The devnets we run are butterfly, interop, etc.

**Comment by jennijuju** [comment]
> Every network we setup has a faucet, The devnets we run are butterfly, interop, etc.

Ah didn’t realize we call them devnets instead testnet , thanks

**Review by arajasek — APPROVED** [review]

**Pull request merged**
