### PR TITLE
Fix/fpost bug

### PR DESCRIPTION
**Pull request by life-i**
When the Candidate is two or more 
the actor_miner got a wrong result for decode the SubmitFallbackPoStParams(Partial of EPostTicket)
Partial always the last Partial

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This is really weird, The problem happens in the array that you are iterating over scandidates and filling out the candidates array. Print out the values right after that and you'll see the problem too. Serialization has nothing to do with it...

Still investigating

**Comment by whyrusleeping** [comment]
Ah, it has to do (for some reason i don't understand yet) with this line:
```
Partial: sc.PartialTicket[:]
```

If you change this loop to say: 
```go
for i, sc := range scandidates {
  c := make([]byte, 32)
  copy(c, sc.PartialTicket[:])
  candidates[i] = types.EPostTicket{
    Partial: c,
    SectorID: ss.SectorID,
    ChallengeIndex: sc.SectorChallengeIndex,
  }
}
```

This is really strange behaviour... but I think that whats happening here is that since these values are not pointers, the variable 'sc' in the loop gets reused across loops. when we slice it in the loop like this, we're making a reference to the memory of that particular variable, which gets changed on the next loop iteration...

Thats scary, and TIL.

cc @kubuxu @magik6k (and  @warpfork just to commisserate about go doing weird things)

**Comment by whyrusleeping** [comment]
It looks like we do this correctly in chain/actors/actor_miner.go SubmitFallbackPoSt (line 487)

**Comment by Kubuxu** [comment]
It is weird but makes sense. We have a struct with an array that is embedded in it. The layout looks like: `[struct, field a, filed b, [array of 32 bytes]]`.

In the loop we re-slice the array which means taking an address of that array, but in this case we take address of temporary loop variable.

**Comment by Kubuxu** [comment]
It makes sense why it happens. The array is embedded in the struct. Reslice gets an address of that embedded array, which turns out to be temporary variable.

**Comment by life-i** [comment]
lol cool

**Pull request closed without merging**
