### PR TITLE
Update to unified go-graphsync v0.9.0

### PR DESCRIPTION
**Pull request by hannahhoward**
# Goals

This is based on https://github.com/filecoin-project/lotus/pull/6375, but rebased on master and updated to go-graphsync v0.9.0 which incorporates all the changes from the v0.6.x branch. It is part of the effort to unify graphsync versions post M1

Blocked by:
- [x] https://github.com/filecoin-project/go-data-transfer/pull/246
- [x] https://github.com/filecoin-project/go-fil-markets/pull/615
- [x] Manual tests
- [x] Testing with miner x

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
Looks like we have some compile errors due to upstream dependency incompatibilities?

**Review by dirkmc — APPROVED** [review]

**Comment by dirkmc** [comment]
Approved modulo updating deps 👍

**Comment by dirkmc** [comment]
Note: Please do not merge until we've had a chance to run a manual test

**Comment by dirkmc** [comment]
Manual tests completed, this PR is ready for merge ✅

**Comment by dirkmc** [comment]
Miner x cohort approved ✅ 
This PR is ready for merge

**Pull request merged**
