### PR TITLE
Fixes in master -> release

### PR DESCRIPTION
**Pull request by jennijuju**
This includes

#6919 
#6909 
#6905

### CODE REVIEW

**Comment by jacobheun** [comment]
Ideally also:
- [ ] https://github.com/filecoin-project/lotus/pull/6937
- [ ] https://github.com/filecoin-project/lotus/pull/6939
- [ ] https://github.com/filecoin-project/lotus/pull/6941

**Comment by raulk** [comment]
Also needed:

- [ ] https://github.com/filecoin-project/lotus/pull/6936

**Comment by jennijuju** [comment]
> Ideally also:
> 
> * [x]  [Update deps for more logging in data transfer and markets #6937](https://github.com/filecoin-project/lotus/pull/6937)
> * [ ]  [Update state machine deps for logging #6941](https://github.com/filecoin-project/lotus/pull/6941)

Did we just remove #6939 or im crazy?

**Comment by jacobheun** [comment]
@jennijuju yes, we closed it because #6936 solves it.

**Comment by raulk** [comment]
Waiting for CI to be green.

**Review by raulk — APPROVED** [review]

**Pull request merged**
