### PR TITLE
Fix fallback chainstore

### PR DESCRIPTION
**Pull request by magik6k**
Fixes https://github.com/filecoin-project/lotus/issues/5975

### CODE REVIEW

**Review by arajasek — APPROVED** [review]
My node no longer crashes when doing this, so approved.

**Review by ribasushi — APPROVED** [review]
Let's 🚢

**Comment by ribasushi** [comment]
@arajasek can we backport this to 0.7? it's fixing a regression arguably...

**Comment by firesWu** [comment]
I use this PR and add env `LOTUS_ENABLE_CHAINSTORE_FALLBACK =1`
When I exec `delete-obj some cid` and restart lotus-daemon, lotus still report error  which is 'block not found'.
I fallback to 1.5.0 version, lotus sync normally.

**Pull request merged**
