### PR TITLE
fix: dont change the latest network version 

### PR DESCRIPTION
**Pull request by jennijuju**
dont think newest network version  should be nv17 in v1.17.2 

(shall only be updated close to v1.18.0 -rc

### CODE REVIEW

**Comment by arajasek** [comment]
Lol, we had this discussion when you were live :cattyping: on #9267 and you wanted to update it!

I'm not sure whether I agree with this change. The biggest reason to keep it is that it makes (most) itests run with the "latest" code. This forces us to iron out all bugs when we integrate a new network version.

This param is otherwise almost exclusively used for devnets and tests. What's your motivation to _not_ update it?

**Comment by jennijuju** [comment]
I remember I asked if we should - and the answer was yes. But I regret it lolol.
- adds confusion to user who reads the code
- I believe devnet is a bit messed up with this, devnet starts at nv16 but there is a couple things we use latest network version

**Comment by geoff-vball** [comment]
@jennijuju Then I think we need to fix the things that are using the wrong network version. We shouldn't have to slow down development because of that

**Comment by jennijuju** [comment]
How does that slow down the development? 
And key reason, the newest network version should stay v16 until v1.18.0

**Comment by geoff-vball** [comment]
@jennijuju Does anyone actually look at the code besides you? :)

The line you changed is autogenerated from the list of network versions in `go-state-types`. We would have to cut a new release of `go-state-types` to change it back. We can if you really want us to, but I strongly believe it's not worth our time.

**Comment by arajasek** [comment]
> I believe devnet is a bit messed up with this, devnet starts at nv16 but there is a couple things we use latest network version

@jennijuju That just sounds like an issue we should fix -- can you share what seems bork? Should be a quick fix.

**Comment by arajasek** [comment]
> The line you changed is autogenerated from the list of network versions in go-state-types. We would have to cut a new release of go-state-types to change it back

Nah, we can just stop autogenerating that line

**Comment by arajasek** [comment]
Killing this in favour of #9351

**Pull request closed without merging**
