### PR TITLE
chore: Fix dead links to docs.filecoin.io

### PR DESCRIPTION
**Pull request by TippyFlitsUK**
## Related Issues
https://github.com/filecoin-project/lotus/pull/8729

## Proposed Changes
This PR updates all dead links within the Lotus repository -  `docs.filecoin.io` to `lotus.filecoin.io`
Replaces https://github.com/filecoin-project/lotus/pull/8729

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [x] This PR has tests for new functionality or change in behaviour
- [x] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

### CODE REVIEW

**Comment by TippyFlitsUK** [comment]
This still needs to be merged. Not too sure why it closed??

**Comment by rjan90** [comment]
Not sure why it closed! I think most of these changes are fine, but would love for someone with more knowledge about the changes in the yaml-files and tools to have a look, if any scripts needs to be run or similar. So probably best to let someone else review those changes :)

**Comment by TippyFlitsUK** [comment]
Thanks Phi!!

**Comment by geoff-vball** [comment]
@TippyFlitsUK This needs a `make jen` and then is good to merge. Sorry for letting this sit for so long!

**Review by geoff-vball — APPROVED** [review]

**Comment by TippyFlitsUK** [comment]
Replaced by https://github.com/filecoin-project/lotus/pull/9301

**Pull request closed without merging**
