### PR TITLE
Update go-libp2p to v0.37.0-pre

### PR DESCRIPTION
**Pull request by MarcoPolo**
For a pre-release sanity check on our next minor release.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [ ] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
Hey @MarcoPolo! Should this still be in draft? Or was the pre-release sanity check okay in this can be opened/reviewed?

**Comment by MarcoPolo** [comment]
The pre-release check passed. This should be ready to review after fixing the conflicts. Sorry, but I won't be able to carry this PR forward right now. However, it should be pretty easy.

**Comment by rjan90** [comment]
> The pre-release check passed. This should be ready to review after fixing the conflicts. Sorry, but I won't be able to carry this PR forward right now. However, it should be pretty easy.

No worries! We can carry it over. Thank you so much for working on this!

**Comment by rjan90** [comment]
Superseded by: https://github.com/filecoin-project/lotus/pull/12729

**Pull request closed without merging**
