### PR TITLE
Add ChainGetMessagesInTipset API

### PR DESCRIPTION
**Pull request by hunjixin**

### CODE REVIEW

**Comment by hunjixin** [comment]
#6610

**Comment by arajasek** [comment]
Build is unhappy, but I think this is a reasonable thing to add.

**Review by magik6k — COMMENTED** [review]
Looks good, but it would be really great to have a test for this.

https://github.com/filecoin-project/lotus/blob/master/itests/nonce_test.go is one of the tests which does some message sending, so it should be easy to write a new test based off it. (when writing itests, after creating a new file in the `itests` directory make sure to run `make circleci` to update the CI config)

**Comment by jennijuju** [comment]
Test awaiting @hunjixin

**Comment by hunjixin** [comment]
@jennijuju  done

**Comment by hunjixin** [comment]
@jennijuju  update

**Review by magik6k — APPROVED** [review]

**Comment by magik6k** [comment]
Thanks for the PR!

**Pull request merged**
