### PR TITLE
fix: bootstrap: Update list to support both IPv4 and IPv6

### PR DESCRIPTION
**Pull request by rjan90**
## Proposed Changes
This PR updates the bootstrap list in the mainnet.pi file to support IPv6 connectivity. Previously, all bootstrap nodes were listed under /dns4, which restricted connections to IPv4 only. By changing the multiaddrs to /dns, we enable libp2p to connect over both IPv4 and IPv6

- Replace `/dns4` with `/dns` in the bootstrap list to support both IPv4 and IPv6 connections.

## Additional Info
- ChainSafe has enabled IPv6 on their bootstrap nodes and confirmed connectivity over IPv6. This change ensures that new nodes can connect over IPv6 if available, improving network robustness and connectivity options.

## Testing:

For the Mainnet bootstrap peers:
```
- lotus net connect /dns/node.glif.io/tcp/1235/p2p/12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt
connect 12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt: success
- lotus net connect /dns/bootstarp-0.1475.io/tcp/61256/p2p/12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt
connect 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt: success
- lotus net connect /dns/bootstrap-venus.mainnet.filincubator.com/tcp/8888/p2p/QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST
connect QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST: success
- lotus net connect /dns/bootstrap-mainnet-0.chainsafe-fil.io/tcp/34000/p2p/12D3KooWKKkCZbcigsWTEu1cgNetNbZJqeNtysRtFpq7DTqw3eqH
connect 12D3KooWKKkCZbcigsWTEu1cgNetNbZJqeNtysRtFpq7DTqw3eqH: success
- lotus net connect /dns/bootstrap-mainnet-1.chainsafe-fil.io/tcp/34000/p2p/12D3KooWGnkd9GQKo3apkShQDaq1d6cKJJmsVe6KiQkacUk1T8oZ
connect 12D3KooWGnkd9GQKo3apkShQDaq1d6cKJJmsVe6KiQkacUk1T8oZ: success
- lotus net connect /dns/bootstrap-mainnet-2.chainsafe-fil.io/tcp/34000/p2p/12D3KooWHQRSDFv4FvAjtU32shQ7znz7oRbLBryXzZ9NMK2feyyH
connect 12D3KooWHQRSDFv4FvAjtU32shQ7znz7oRbLBryXzZ9NMK2feyyH: success
```

## References:
- Issue #11874
- Slack discussion [here](https://filecoinproject.slack.com/archives/CP50PPW2X/p1718360407181249)

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
@TippyFlitsUK Could you do the testing for connecting to the Bootstrap-peers with the `/dns`-address here: https://github.com/filecoin-project/lotus/pull/12103/files, and just confirm they are succesful. I do not have my Calibnet-node up to sync at this moment.

**Comment by TippyFlitsUK** [comment]
> @TippyFlitsUK Could you do the testing for connecting to the Bootstrap-peers with the `/dns`-address here: https://github.com/filecoin-project/lotus/pull/12103/files, and just confirm they are succesful. I do not have my Calibnet-node up to sync at this moment.

Will do Phi! 👍

**Comment by TippyFlitsUK** [comment]
@rjan90 

Calibration - All good

```
lotus net connect /dns/calibration.node.glif.io/tcp/1237/p2p/12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x
connect 12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x: success

lotus net connect /dns/bootstrap-calibnet-0.chainsafe-fil.io/tcp/34000/p2p/12D3KooWABQ5gTDHPWyvhJM7jPhtNwNJruzTEo32Lo4gcS5ABAMm
connect 12D3KooWABQ5gTDHPWyvhJM7jPhtNwNJruzTEo32Lo4gcS5ABAMm: success

lotus net connect /dns/bootstrap-calibnet-1.chainsafe-fil.io/tcp/34000/p2p/12D3KooWS3ZRhMYL67b4bD5XQ6fcpTyVQXnDe8H89LvwrDqaSbiT
connect 12D3KooWS3ZRhMYL67b4bD5XQ6fcpTyVQXnDe8H89LvwrDqaSbiT: success

lotus net connect /dns/bootstrap-calibnet-2.chainsafe-fil.io/tcp/34000/p2p/12D3KooWEiBN8jBX8EBoM3M47pVRLRWV812gDRUJhMxgyVkUoR48
connect 12D3KooWEiBN8jBX8EBoM3M47pVRLRWV812gDRUJhMxgyVkUoR48: success
```

Mainnet - Is `bootstarp-0.1475` a typo? - Doesn't work with either spelling

```
lotus net connect /dns/bootstarp-0.1475.io/tcp/61256/p2p/12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt
connect 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt: failure
ERROR: failed to dial: failed to dial 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt: all dials failed
  * [/ip4/10.5.240.123/tcp/6000] dial tcp4 10.5.240.123:6000: i/o timeout
  * [/ip4/103.163.186.26/tcp/61256] dial tcp4 103.163.186.26:61256: i/o timeout
  * [/ip4/103.163.186.23/tcp/61256] failed to negotiate security protocol: context deadline exceeded
  
lotus net connect /dns/bootstrap-0.1475.io/tcp/61256/p2p/12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt
connect 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt: failure
ERROR: failed to dial: failed to dial 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt: all dials failed
  * [/ip4/10.5.240.123/tcp/6000] dial tcp4 10.5.240.123:6000: i/o timeout
  * [/ip4/103.163.186.26/tcp/61256] dial tcp4 103.163.186.26:61256: i/o timeout
  * [/ip4/103.163.186.23/tcp/61256] failed to negotiate security protocol: context deadline exceeded
```


```
lotus net connect /dns/node.glif.io/tcp/1235/p2p/12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt
connect 12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt: success

lotus net connect /dns/bootstrap-venus.mainnet.filincubator.com/tcp/8888/p2p/QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST
connect QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST: success

lotus net connect /dns/bootstrap-mainnet-0.chainsafe-fil.io/tcp/34000/p2p/12D3KooWKKkCZbcigsWTEu1cgNetNbZJqeNtysRtFpq7DTqw3eqH
connect 12D3KooWKKkCZbcigsWTEu1cgNetNbZJqeNtysRtFpq7DTqw3eqH: success

lotus net connect /dns/bootstrap-mainnet-1.chainsafe-fil.io/tcp/34000/p2p/12D3KooWGnkd9GQKo3apkShQDaq1d6cKJJmsVe6KiQkacUk1T8oZ
connect 12D3KooWGnkd9GQKo3apkShQDaq1d6cKJJmsVe6KiQkacUk1T8oZ: success

lotus net connect /dns/bootstrap-mainnet-2.chainsafe-fil.io/tcp/34000/p2p/12D3KooWHQRSDFv4FvAjtU32shQ7znz7oRbLBryXzZ9NMK2feyyH
connect 12D3KooWHQRSDFv4FvAjtU32shQ7znz7oRbLBryXzZ9NMK2feyyH: success
```

**Comment by rjan90** [comment]
> Mainnet - Is bootstarp-0.1475 a typo? - Doesn't work with either spelling

It is actually not a typo, I think it's a play on the word bootstrap. Interestingly, it worked for me to connect to that bootstrap node on mainnet, so it might be some local variances.

**Review by rvagg — APPROVED** [review]

**Pull request merged**
