### PR TITLE
storagefsm: Fix batch deal packing behavior

### LINKED ISSUE #5077: Sectors in WaitDeals does not transition to sealing when full
**Describe the bug**
Sectors in _WaitDeals_-state does not automatically transition to sealing when they are full (at capacity), they keep waiting in the same state.

**To Reproduce**
1. Fill up a sector in _WaitDeals_-state with deals so they are full.
2. When the sectors is full, it's still waiting in WaitDeals-state:
```

SectorID:	1088
Status:		WaitDeals
CIDcommD:	<nil>
CIDcommR:	<nil>
Ticket:		
TicketH:	0
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Proof:		
Deals:		[1395946 1396614 1396655 0 1396798 1396844 1396862 1401086 1401118 1401123 1401132 1401139 1401148 1401179 1401185 1401207 1401225 1401235 1401245 1401255 1401258 1401263 1401376 1401380 1401383 1401388 1401399 1401406 1401425 1401436 1401552 1401555 1401561 1401851]
Retries:	0
--------
Event Log:
0.	2020-11-30 18:59:00 +0100 CET:	[event;sealing.SectorStart]	{"User":{"ID":1088,"SectorType":8}}
1.	2020-11-30 18:59:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqajznqvnvteeyvmhordx7qtxasa26orgpfilfvim5mhyfmvaz5uei"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceapwgmdyp7auyszdfu724onllpf2ktwvdhvvkhwnxbm4wqv2ws7qu"},"DealID":1395946,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
2.	2020-11-30 19:44:13 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqk4alwhrnklqfulyadp4sjklwujajiyad3fsqorckqlq3s33kagpi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceb7wwkfnnep57ygpuaqu7hjukkzv44botxxhulgmfqhdqoprl64ny"},"DealID":1396614,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
3.	2020-11-30 19:44:50 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":536870912,"PieceCID":{"/":"baga6ea4seaqaektvzh336tgm7x3wm5ss63jrebb6loo45oa2zmm3hqry4rixaba"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceamytg7bn3ld5ki7cnvtibnaadiqy7z6adli4qg46xybne4qm52mw"},"DealID":1396655,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
4.	2020-11-30 19:50:18 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":536870912,"PieceCID":{"/":"baga6ea4seaqdsvqopmj2soyhujb72jza76t4wpq5fzifvm3ctz47iyytkewnubq"}},"DealInfo":null}}}
5.	2020-11-30 19:50:59 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqaxsle6wid46thnrpgnquq7vb5b42azercdrpxmmqol7o6yfzigoi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaced6ejlq6hs5uxzuab3ecbowrmupelbvllgkuauxdxpgplplt75ayi"},"DealID":1396798,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
6.	2020-11-30 19:51:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqip5buqiqjen5zlul6vclc6sv4v5uz7b2xur7mwqzg4lzex2myyji"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecdk2ohedisjr674uwbpp373jzzjksfvwvxyeagu4fjs5mslwbe34"},"DealID":1396844,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
7.	2020-11-30 19:52:41 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqo2jrzaunlwocdbz72bssonv7gjtblmrlcwxvbdrjmlbo735d3kai"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebhnhn4s3oeu4ymjbgue2xqg2ltwxuk4b6i2mllvr5opzavwyxcv2"},"DealID":1396862,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
8.	2020-11-30 22:35:41 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqpfa2q7xln32qmmvbvhcpjcnd35fwmotg6obiob6ymdpf5auebeii"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedk4ywq22rqbpvioudziamv4kz7d2wxokblpnznpvaxlujb4dmxgg"},"DealID":1401086,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
9.	2020-11-30 22:38:40 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqlbmtb5clbgrfpemdxcfqtswzgoeoakrzo3bjtsqv5mwhsvjajglq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebcpic7rysumi3lvdxhjz6aya7bfztutivfa6jlekathsikznjeqw"},"DealID":1401118,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
10.	2020-11-30 22:39:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqcfb66fqfq452fgtpbg4vcxnobmien6u4pese6ygyin73y26scygy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacech6i4pmkbujk2b37rsu25z5idvzavzbhjl6gtmguydyigkjzknmu"},"DealID":1401123,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
11.	2020-11-30 22:40:41 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqgczrz2jpcvia5qzdj4ygjchrv3i5bi4aeg4wpiq622cmoyl5rshi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedurbm6q4fhegr3asc3vszoe4fh2qf5gfvrm5fycbt3flk2446yca"},"DealID":1401132,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
12.	2020-11-30 22:41:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqd6tlet5dh4tjjk2iajeduj5bd6xbsdghjdfdqoy7xil6op36jspq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecqjmi3huf2tyemwlhd7gba6uhrcsrxtarsm7nwitvvcyqtx55jsu"},"DealID":1401139,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
13.	2020-11-30 22:42:44 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqj7dojmvx4vgavo6i4677dhcpsgajk3lu3qse2xlpkjthufr4omaa"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceamac6ogqad6rhdzuvsvmjnwdf3cadzr4qqea5ds6tr4d4akux7zs"},"DealID":1401148,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
14.	2020-11-30 22:45:40 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqmbqnevcvtpq6fvknhhrfbwlzowgq7fn5ssjy2mnj7nlgiayxoyey"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedxif64qq35wem7gljxnpvlpcpxqhnjukxx22zfu7rrfhivurnxdq"},"DealID":1401179,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
15.	2020-11-30 22:46:40 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqjsp6ydjd4daplqti6qimx3mpkh5eydmuwoc5odaormhwdzmfeypa"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacea3hqqd27tspugz3v3qqixfo4ll3qwbzobfjlnli77soe5ccrxw4u"},"DealID":1401185,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
16.	2020-11-30 22:48:41 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqe3wkv3yrrqobrkbiqbtg7gpbqxzoj7pmkvc44wsayn57gmv2fsmi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecwqbkc7d2zvkjank7escoawkgrcayc3tsbl2wbk3o3ymzpebh3uy"},"DealID":1401207,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
17.	2020-11-30 22:50:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqpdyu5dzyln2c3a253zwky54kea7kp6vlosu4fewj5nxvuxtltcla"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceapc3afpysg7g2o5k36pvtze5nm5hvw7j7yohxdiuzcsefwyp6rnu"},"DealID":1401225,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
18.	2020-11-30 22:52:14 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqaskoz46k3dqyluwi2gdxuzvjwuof26vj2c4qwvzrdozrajymjapq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecbqhjkeoeqkfwev3qc4mm43lr3b7sxkgsbp57jnocmqjiv2ebg3g"},"DealID":1401235,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
19.	2020-11-30 22:53:13 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqcclxh7cehe3gwgfuyctgr5joxdzo46svjche3upjdqy7qkt3l6oy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceaskc7ypgxoorzbl2aczriwj6ky72d4lmxa7qovdufu3oyefxll54"},"DealID":1401245,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
20.	2020-11-30 22:54:11 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqci3kae2iw4ki65fjodvjdbfucklmyoxqwtxuwjcvsywvv4hpiacy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecjwxc5gurdin33zpemwknpo2okyzadlszr52r64zqyh4a2jxrcbc"},"DealID":1401255,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
21.	2020-11-30 22:54:51 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqnudofwka7uq2znvcwab6k34jw7wsqrsb2mu3rhzm3hwk55v6dqbq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacec2bqm3chl63ern5zkpfi3gibzhcbkvmof5lmkotbgiuh3mpaw3d2"},"DealID":1401258,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
22.	2020-11-30 22:55:39 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqa4uuoxo65hkembhgib2kh5zbu5rnid2drfzyosxjcfr2hta3ligy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacean7jku2557yo5mmkoguhjcbp6kq5uwgtxvvzosy3hfb3zvv4wwos"},"DealID":1401263,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
23.	2020-11-30 22:56:43 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqdssvxfyp2x7ovmilt5gcid3ozbjhcjsyciebmpvsmtufqm7mh4ay"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceahpzgdbrqa67sfhg4rodz22da3q3h752zblgbfnjf55g2wpmenpa"},"DealID":1401376,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
24.	2020-11-30 22:57:26 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqpnjt5oli5dab7yk5z6vbx5whgegrpr3l3kojbx7ihr4sgbfqkuny"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedjehqbjy5gqhsdh4ibvs3xt3zrrfi42jurw3qz4p3r77njkqgg7k"},"DealID":1401380,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
25.	2020-11-30 22:58:07 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqcaltwdlubnsxrmzk2gl6x3ad34glj5442zuj3cthgcvnolplkupy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacecq2au5wyuhk52q67pzelka7qj23cmkigaqzvymtadquclbqglpqs"},"DealID":1401383,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
26.	2020-11-30 22:58:48 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqbevjsfaiiaced65ymdohkyxo3c5pzz7qhwndt4jlmnndh5nkqeiq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceahf2rwsx2ii5vmyaacq47dfmjdu22prg4sneroyotwycfz3hqpgo"},"DealID":1401388,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
27.	2020-11-30 22:59:40 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqhg4dv5vu35k2oemaz67243njixuqjxv6mv2oiqkwvdwtxn35qmki"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedm25yh634p7gaui4e3w7e2arta5et6qtwdccc7y3zag5tpshcj3u"},"DealID":1401399,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
28.	2020-11-30 23:01:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqere3imo76qjqdj4xfg7ert4n6vr5pdnztrq4rgcvthzlmxfyzinq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebr4wxsgtcbjnv3lupxspwdrmr2viyzev7jcnivcjxltuityznzg4"},"DealID":1401406,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
29.	2020-11-30 23:02:42 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqddcq755ywyk5obdcubm64pfs62notbhugrqfapmux3edrjpgwohi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacea2jutbuugffhgu2tltxdeuzlkduvgh4abccaaibnjgdtv7d2aexk"},"DealID":1401425,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
30.	2020-11-30 23:04:10 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqfgfl2esp6zurahk3v2znb5qritxkrhzx523cbjt6wncpab4yxaja"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebqcy7d3lxntx5gdnyhkbzdjx6ibaebguntj2tjbsvfsclgr7idf6"},"DealID":1401436,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
31.	2020-11-30 23:05:40 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqk5hsqncrh53rkwoxlcbxtkldyfffzak37zdqr7ici4zp2w4l62jy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebiwxsbmxztrqvkevfeje6pqvb6mpbe5vm6wmxl7wd6lxwrtjt7cg"},"DealID":1401552,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
32.	2020-11-30 23:06:01 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":536870912,"PieceCID":{"/":"baga6ea4seaqgy5z33dq5dyjsseg44vtvasi7xplh5ckeng3boh5vngbk2m5lqgy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebttg4uz6kymciqayrjgpnfivbbgdy2oj2c6vbumz4ck6yf3q4qo4"},"DealID":1401555,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
33.	2020-11-30 23:06:51 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":536870912,"PieceCID":{"/":"baga6ea4seaqkxit3dwpcivwu3yq6kpqezqqpzkfm7rbulw4yvxtyeu5n6xxw6ei"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacedjlqbr6k2yw3vpsusphwy3y6fwqsyjptujlj7quczaa6j7t6xfsc"},"DealID":1401561,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}
34.	2020-11-30 23:29:41 +0100 CET:	[event;sealing.SectorAddPiece]	{"User":{"NewPiece":{"Piece":{"Size":1073741824,"PieceCID":{"/":"baga6ea4seaqococnsnura23tom5tmbxgdbfnplm5ziyqlhbqwyuuk3qxp3ekocy"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceammgxqnu6rt4dnzg47rb2s73fkf6n7ugmvhvtb4arnocikb3nv3q"},"DealID":1401851,"DealSchedule":{"StartEpoch":285000,"EndEpoch":1336683},"KeepUnsealed":true}}}}

```

**Expected behavior**
Expected the sector to automatically transition to sealing.

**Version (run `lotus version`):**
Daemon:  1.2.1+git.df66f48f6+api1.0.0
Local: lotus version 1.2.1+git.df66f48f6

### LINKED ISSUE #6010: [Deal Making Issue] Batch import deal creates an extra sector that stuck in WaitDeals
Today I imported 3 offline deals and force publish by executing lotus-miner storage-deals pending-publish --publish-now

I would expect it creates 3 sectors but it actually created 4 sectors, the last sector stuck in WaitDeals forever, until I manually remove it.

`615  WaitDeals  NO       NO      n/a                             CC `

```
lotus-miner sectors status --log 615
SectorID:	615
Status:		WaitDeals
CIDcommD:	<nil>
CIDcommR:	<nil>
Ticket:		
TicketH:	0
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Proof:		
Deals:		[]
Retries:	0
--------
Event Log:
0.	2021-04-10 21:04:30 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":615,"SectorType":8}}
```

### LINKED ISSUE #6013: Batch published deals do not get packed into sectors as expected
regarding:

https://filecoinproject.slack.com/archives/G01KU7G441Y/p1618134221295100

when batch publishing deals MaxWaitDealsSectors needs to be set to 1 if a miner wants all published deals in the same sector. as soon as MaxWaitDealsSectors > 1 the deals get spread out over  [up to]  MaxWaitDealsSectors sectors.

Expected/wanted behavior:

lotus-miner packing deals into sectors as it can find space without creating [up to] MaxWaitDealsSectors sectors.

[edit]

as reference about how this behaves:

https://filecoinproject.slack.com/archives/G01KU7G441Y/p1616110446225200?thread_ts=1615892104.004200&cid=G01KU7G441Y

### PR DESCRIPTION
**Pull request by magik6k**
Fixes #6013
Fixes #5077
Fixes #6010

### CODE REVIEW

**Comment by stuberman** [comment]
I hope to test this later with 1.7.0-rc1

**Comment by stuberman** [comment]
Updated and running deals now
`lotus-miner version`

> Daemon: 1.7.1-dev+mainnet+git.7f2030d41+api1.0.1
> Local: lotus-miner version 1.7.1-dev+mainnet+git.7f2030d41

`lotus-worker info`

> Worker version: 1.0.0
> CLI version: lotus-worker version 1.7.1-dev+mainnet+git.7f2030d41

1st things I noticed:

1. Published now: 6x32GiB deals
2. This created 6xAP plus 4xWaitDeals sectors all at once
3. MaxDealsPerPublishMsg = 16
4. Worker showing repeated WARN messages: “negative reserved storage: p.reserved=206158430208, reserved: -393216”

**Comment by stuberman** [comment]
**More updates:**
I recently received 14 more small deals. 13 deals were batch published, and two WaitDeals sectors created. The first WaitDeals sector (1078) accepted all 13 deals using AddPiece.
Both sectors continued to remain in WaitDeals. When the 14th deal came in, I pushed it to publish once it finished transferring and it was added to sector 1078.

I think this is exactly the behavior we are looking for. (Although sector 1079 is superfluous at this point and I expect to remain in WaitDeals status until it both gets deals and the SealDelay timer expires. @Magik6k 

> 1078 WaitDeals  NO    NO   n/a                14        
> 1079 WaitDeals  NO    NO   n/a                CC

**Comment by jennijuju** [comment]
We need to make sure that smaller sized deals won't end up on a million of new sectors and waiting for to be sealed when the MaxWaitDealsSectors is set to a non-1 number

**Comment by arajasek** [comment]
Context from @jennijuju : Magik is pretty sure there's a bug in this that we need to 🕵️‍♀️

**Comment by magik6k** [comment]
The thing with empty wait-deals sectors happened in CI -> https://app.circleci.com/pipelines/github/filecoin-project/lotus/14510/workflows/7a9b07d5-6535-40fd-bdf1-61938cc92f89/jobs/152549/tests#failed-test-0

**Review by arajasek — APPROVED** [review]
SGWM

**Comment by jennijuju** [comment]
More testing is required on this PR and we wont be backporting it for v1.10.0, but it should be merged for v1.11.0

**Comment by jennijuju** [comment]
Many miners have been running this for more than two weeks and this fixed issue for them. It is now crucial for miners that are actively making deals, especially to have sectors created properly. Therefore, we should backport it to v1.10.0.

**Pull request merged**
