### PR TITLE
re-enable baseFee lower bound check

### PR DESCRIPTION
**Pull request by vyzo**
we are past the fork now and in an hour we won't have negative chains any more, so it is time to re-enable this very important check.

### CODE REVIEW

**Comment by vyzo** [comment]
let's wait a little to ensure baseFee is under control, and then we can merge.

**Comment by vyzo** [comment]
rebased on master and added a more conservative factor (100x) for the strict check per magik's request.

**Comment by vyzo** [comment]
linter complaint comes from some completely unrelated package, i will ignore.

**Comment by vyzo** [comment]
the test failure is completely unrelated:
```
=== Errors
conformance/chaos/actor_test.go:22:26: undefined: adt.Empty
```

**Comment by vyzo** [comment]
rebased on master yet another time, to incorporate the fix for the broken tests.

**Comment by vyzo** [comment]
rebased on master and fixed conflicts.

**Review by magik6k — APPROVED** [review]

**Review by Kubuxu — APPROVED** [review]

**Pull request merged**
