### PR TITLE
Remote wallet backends

### PR DESCRIPTION
**Pull request by magik6k**
This implements https://github.com/filecoin-project/lotus/issues/2016, not fully done yet, and has some ux bugs, but it should generally work

### CODE REVIEW

**Comment by whyrusleeping** [comment]
It's like magic.

**Comment by arash009** [comment]
Looking forward to this getting in.

**Comment by magik6k** [comment]
Depends on HTTP JsonRPC client support -> https://github.com/filecoin-project/go-jsonrpc/pull/30

**Comment by magik6k** [comment]
It Works!

screencap 2020-10-09T02:47:12Z

**Review by whyrusleeping — APPROVED** [review]
This looks really great! Lets land it!

**Pull request merged**
