### PR TITLE
feat: add StateMinerDeadlines to gateway

### PR DESCRIPTION
**Pull request by qwdsds**
## Proposed Changes

Add StateMinerDeadlines to gateway.

https://github.com/filecoin-project/lotus/discussions/11693

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Review by rvagg — APPROVED** [review]

**Comment by rvagg** [comment]
lgtm as per discussion in https://github.com/filecoin-project/lotus/discussions/11693

**Review by magik6k — CHANGES_REQUESTED** [review]
For this to work you'll also need to add a proxy method in https://github.com/filecoin-project/lotus/blob/master/gateway/proxy_fil.go which just needs to check that the tipset is recent enough. Without that this method won't work correctly on lotus-gateway

**Comment by qwdsds** [comment]
> For this to work you'll also need to add a proxy method in https://github.com/filecoin-project/lotus/blob/master/gateway/proxy_fil.go which just needs to check that the tipset is recent enough. Without that this method won't work correctly on lotus-gateway

StateMinerDeadlines are already in this [gateway/proxy_fil.go](https://github.com/filecoin-project/lotus/blob/master/gateway/proxy_fil.go#L490C1-L498C1)

**Comment by rvagg** [comment]
still seems fine to me, needs @magik6k to re-review

**Review by Stebalien — APPROVED** [review]
Confirmed that this exists in `proxy_fil.go` and the lookback limit is being enforced.

**Pull request merged**
