### PR TITLE
go.sum

### PR DESCRIPTION
**Pull request by waynewyang**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Hrm... I wonder why our `go mod tidy` CI rule didnt catch this before merging

**Comment by Kubuxu** [comment]
According to my Go, `go.sum` is complete on master.

**Comment by Kubuxu** [comment]
@waynewyang what is your Go version `go version`.

**Comment by magik6k** [comment]
(I have `go version go1.13.3 linux/amd64`, and also see this)

Merging now, it's probably not worth the time to 'debug' this

**Comment by waynewyang** [comment]
@Kubuxu 
```
waynewyang:lotus waynewyang$ go version
go version go1.13.1 darwin/amd64
```

**Comment by Kubuxu** [comment]
That makes sense. I recommend updating to 1.13.3, it has some important fixes.

**Pull request merged**
