### PR TITLE
fix: cherrypick/conflict wrongfully resolved

### PR DESCRIPTION
**Pull request by jennijuju**
seems like the right code should be https://github.com/filecoin-project/lotus/blob/58900a70333a11a903cf9fe3f29e6a5c309cb000/node/impl/full/eth.go#L251-L268

but https://github.com/filecoin-project/lotus/blob/99749e9b9bbe7d2ec89807d342fa63e3f1a4f2d8/node/impl/full/eth.go#L251-L265  was outdated

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]
Would explain the failing test.

**Comment by Stebalien** [comment]
Looks like something is still wrong with the go.mod file.

**Comment by jennijuju** [comment]
> Would explain the failing test.

I thought was flakey..... my bad...

**Comment by Stebalien** [comment]
> I thought was flakey..... my bad...

So did I.

**Pull request merged**
