### PR TITLE
update libp2p dependencies

### PR DESCRIPTION
**Pull request by vyzo**

### CODE REVIEW

**Comment by raulk** [comment]
(Await an actual contributor's approval.)

**Comment by vyzo** [comment]
Hrm, we have an actual test failure that seems related:
```
Failed
=== RUN   TestUnsignedMessageVectors
    TestUnsignedMessageVectors: vectors_test.go:23: could not decode: varints larger than uint63 not supported: invalid address payload
--- FAIL: TestUnsignedMessageVectors (0.00s)
```

**Comment by vyzo** [comment]
@raulk any idea whether this is coming from libp2p and friends? The test seems benign enough and doesn't use any libp2p stuffs directly.

**Comment by raulk** [comment]
@whyrusleeping says it's not a meaningful breakage as the test vector is random garbage. Test needs to be fixed.

**Comment by vyzo** [comment]
I am going to disable it for now, as this is critical to merge and the serialized vectors are in an external project and need to be fixed.

**Pull request merged**
