### PR TITLE
Create LotusCommandLines.md

### PR DESCRIPTION
**Pull request by MitchellSoo**
Add command lines markdown document for lotus v0.3.0.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
In order to keep this more easily updated, I would prefer to have a script that we could run to generate this.

Additionally, we will want this featured on the lotus docs website, meaning it should go inside the documentation folder along with the other docs

**Comment by MitchellSoo** [comment]
> Thanks for the PR!
> 
> In order to keep this more easily updated, I would prefer to have a script that we could run to generate this.
> 
> Additionally, we will want this featured on the lotus docs website, meaning it should go inside the documentation folder along with the other docs

Yes, I did use my script to generate the document and format it to fit markdown on github. Where I should commit the script to? Also documentation folder?

**Comment by whyrusleeping** [comment]
Lets put it into the scripts folder for now.

**Comment by arajasek** [comment]
@MitchellSoo Sorry about the super-long delay here! Can you please add the script you used to `scripts`, rebase onto `master`, and re-run the script (I'm guessing it a lot has changed).

**Comment by MitchellSoo** [comment]
> @MitchellSoo Sorry about the super-long delay here! Can you please add the script you used to `scripts`, rebase onto `master`, and re-run the script (I'm guessing it a lot has changed).

I have added it as PR #2467 .

**Comment by magik6k** [comment]
Duplicate of https://github.com/filecoin-project/lotus/pull/2467

**Pull request closed without merging**
