### PR TITLE
api: Invert StartDealParams fast retrieval param

### PR DESCRIPTION
**Pull request by magik6k**
This should set better default expectations

Fixes https://github.com/filecoin-project/lotus/issues/3017

### CODE REVIEW

**Comment by momack2** [comment]
Isn't different experiences between the API and CLI still confusing? Seems like we should align them to all say the same thing and have the same default value. With this change 'setting the fast retrieval flag to true' could actually mean opposite things. Is it hard to make the default value true here? that would be my preference...

**Comment by ribasushi** [comment]
@momack2 the way the RPC pipeline is built, there is no way to signal "not set" - there's just `Set=true` and `Set=false  / unset` without an ability to tell the two sub-states apart

@magik6k "fast/slow-retrieval" is too far removed from what actually happens anyway. If we are to rename things we should probably harmonize everything towards `RemoveUnsealedSource:` => `false(default)` / `true`

**Comment by momack2** [comment]
From @whyrusleeping "If we really want to make this change, i think adding a JSONUnmarshaler method to the struct in question that defaults the value to true seems more reasonable" I would be happy with that change. 

Anything involving renaming across the cli/api seems more involved and complex and I'd encourage us deferring because the changes across the existing code (and the messaging) would be much more difficult to wrangle. If adding the unmarshaler isn't an option, let's just close my request and document it better.

**Comment by magik6k** [comment]
JSONUnmarshaler sounds better, closing this PR for now

**Pull request closed without merging**
