### PR TITLE
chore: remove unmaintained bootstrappers

### PR DESCRIPTION
**Pull request by rjan90**
## Proposed Changes
Remove unmaintained bootstrappers 

## Additional Info
As noted in this [thread on Slack](https://filecoinproject.slack.com/archives/C039RBG3RPC/p1715255422205499), these three bootstrappers has been confirmed to no longer be maintained.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
@smagdali I´m not its a actual typo or not in https://github.com/filecoin-project/lotus/pull/11983/commits/54d637a29d971425c27743ba5686ea16b6423383.

The PR added by the 1475-team here, points to it actually being bootstarp: https://github.com/filecoin-project/lotus/pull/8495. Might be a funny twist to similar to HODL.

**Comment by LesnyRumcajs** [comment]
> @smagdali I´m not sure it is an actual typo or not in [54d637a](https://github.com/filecoin-project/lotus/commit/54d637a29d971425c27743ba5686ea16b6423383).
> 
> The PR added by the 1475-team here, points to it actually being bootstarp: #8495. Might be a twist to the name, similar to HODL.

Is it still maintained?

```
❯ forest-tool net ping /dns4/bootstarp-0.1475.io/tcp/61256/p2p/12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt
PING /dns4/bootstarp-0.1475.io/tcp/61256/p2p/12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt
Ping failed: error=Ping timeout
Ping failed: error=Ping timeout
```

**Comment by rjan90** [comment]
> Is it still maintained?

It seems like it is not maintained anymore. But I think we should wait for confirmation from Fatman, who reached out to them, before removing it.

**Comment by smagdali** [comment]
line 5 has a typo 'bootstarp' -> 'bootstrap'

> @smagdali I´m not sure it is an actual typo or not in [54d637a](https://github.com/filecoin-project/lotus/commit/54d637a29d971425c27743ba5686ea16b6423383).
> 
> The PR added by the 1475-team here, points to it actually being bootstarp: #8495. Might be a twist to the name, similar to HODL.

yup. usual lesson to not take anything at face value in this ecosystem. apologies.

**Review by ZenGround0 — APPROVED** [review]

**Review by rvagg — APPROVED** [review]

**Pull request merged**
