### PR TITLE
clean/mv-actors-bundle

### PR DESCRIPTION
**Pull request by snadrus**
## Related Issues
The 40MB+ of actors bundle content should not be implicitly included in everything that wants to know the build version.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by snadrus** [comment]
All present dependencies of curio, broken down by package: 
[deps.json](https://github.com/filecoin-project/lotus/files/15018061/deps.json)

Following the goal of removing lotus/build/actors:
It's imported by:
github.com/filecoin-project/lotus/chain/consensus/filcns
   github.com/filecoin-project/lotus/node 
      github.com/filecoin-project/lotus/curiosrc/market/lmrpc <-- TODO Use the node.* resources without node
   github.com/filecoin-project/lotus/chain/gen
      github.com/filecoin-project/lotus/curiosrc/winning <--- TODO Use the gen.* resources without node
      github.com/filecoin-project/lotus/storage
          github.com/filecoin-project/lotus/node

github.com/filecoin-project/lotus/node/bundle
   github.com/filecoin-project/lotus/chain/gen/genesis
        github.com/filecoin-project/lotus/node/modules/testing  
            github.com/filecoin-project/lotus/node <-- already set to prune
   github.com/filecoin-project/lotus/chain/vm
        github.com/filecoin-project/lotus/chain/consensus
        github.com/filecoin-project/lotus/chain/messagepool
        github.com/filecoin-project/lotus/chain/stmgr
        github.com/filecoin-project/lotus/node/impl/full
        github.com/filecoin-project/lotus/chain

These last 5 aren't fully investigated, but mostly appear to connect back to the 3 "prune points" identified.

**Comment by snadrus** [comment]
lprpc.go:  impl.StorageMinerAPI

node/modules is needed by: 
    curio/deps:  SealProofType()
    guidedsetup: JWTSecretName
    tasks: GetParams()

**Comment by snadrus** [comment]
This'll get rid of the actors bundle. Other weight loss could include:
sqlite
wasmparser
Rust appears huge as well
go-fil-markets comes along for the ride

According to: go tool nm -size -sort size curio|less

**Comment by rjan90** [comment]
@snadrus Is this part of decoupling/moving curio to a seperate codebase? Lotus the chain still needs the actor-bundle so its unclear if this is something that should be merged in this repo

**Comment by snadrus** [comment]
Everything here is about making a clear distinction and general code
cleanup. Nothing here is intended to be a breaking change.

**Comment by LexLuthr** [comment]
Closing as this has been ported.

**Pull request closed without merging**
