### PR TITLE
chore: cli: cleanup cli 

### PR DESCRIPTION
**Pull request by rjan90**
## Related Issues
Standarize cli/code functions similar to: https://github.com/filecoin-project/lotus/pull/9317

## Proposed Changes
- Change to cctx.NArg() instead of cctx.Args().xxx
- Add ArgsUsage to commands that was missing it
- Add check for args and print help on functions that did not have it

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by geoff-vball** [comment]
Thanks, this looks great! Just needs a `make docsgen-cli`

**Comment by geoff-vball** [comment]
@rjan90 I've rerun the flaky tests a few times. It looks like the remaining failures are real. Looks like strictly checking the number of params in a few cases caused problems. Could be the test that's wrong

**Comment by rjan90** [comment]
@geoff-vball Yeah, looks like there is issues with the `lotus wallet markets add` test, I will check it up tomorrow

**Comment by rjan90** [comment]
Looks like all checks have passed now. I ended up having a not so strict ArgCheck for the `lotus wallet markets add` cmd. The failure seemed to come from a discrepency in the CLI and test for [MarketAddBalance](https://pkg.go.dev/github.com/filecoin-project/lotus/api/v0api#FullNode.MarketAddBalance).

While MarketAddBalance needs `wallet`, `addr` and `amt`, the cli-function only asks for amt and defaults to the default address for `wallet` and `addr` if not anything else is specified through the options `--address` and `--from`. So there is potentially an edge case failure in the cli, where it will fail if lotus has not an default adress set and the wallet and addr is not set through the options.

**Review by geoff-vball — APPROVED** [review]

**Comment by geoff-vball** [comment]
Awesome, that's totally fine by me.

**Pull request merged**
