### PR TITLE
fix dead lock between publk and heaviestLk while too many SetHead

### PR DESCRIPTION
**Pull request by hunjixin**

### CODE REVIEW

**Comment by jennijuju** [comment]
This could be valid and  needs 👁️ to confirm.

**Comment by hunjixin** [comment]
> This could be valid and needs 👁️ to confirm.

difficult to reproduce this bug

**Comment by hunjixin** [comment]
> > This could be valid and needs 👁️ to confirm.
> 
> difficult to reproduce this bug.  continue to establish a lot of connections have more chance to reproduce the issue

**Comment by magik6k** [comment]
This should be fixed by https://github.com/filecoin-project/lotus/pull/6526

**Pull request closed without merging**
