### PR TITLE
Update FFI to 0.30.1

### PR DESCRIPTION
**Pull request by magik6k**
WIP Something about the update makes tests sad:
```
--- FAIL: TestSyncSimple (0.08s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe20d76]

goroutine 37 [running]:
testing.tRunner.func1.1(0x2c98320, 0x54d5ac0)
	/usr/lib/go/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc00042e900)
	/usr/lib/go/src/testing/testing.go:943 +0x317
panic(0x2c98320, 0x54d5ac0)
	/usr/lib/go/src/runtime/panic.go:975 +0x41b
github.com/filecoin-project/filecoin-ffi/generated.(*FilAggregateResponse).Deref(0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/extern/filecoin-ffi/generated/cgo_helpers.go:227 +0x26
github.com/filecoin-project/filecoin-ffi.Aggregate(0x0, 0x0, 0x0, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/extern/filecoin-ffi/bls.go:75 +0x3de
github.com/filecoin-project/lotus/chain/gen.aggregateSignatures(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/gen/mining.go:152 +0x2f8
github.com/filecoin-project/lotus/chain/gen.MinerCreateBlock(0x3311a00, 0xc00012c018, 0xc00028af30, 0xc00000f4c0, 0xc0002d3458, 0x0, 0x0, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/gen/mining.go:100 +0x18f1
github.com/filecoin-project/lotus/chain/gen.(*ChainGen).makeBlock(0xc0006a1450, 0xc00028fd40, 0xc00040a6e5, 0x3, 0xc0002de2a0, 0xc0002d8b40, 0xc0002d8ae0, 0x1, 0x1, 0x1, ...)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/gen/gen.go:420 +0x324
github.com/filecoin-project/lotus/chain/gen.(*ChainGen).NextTipSetFromMiners(0xc0006a1450, 0xc00028fd40, 0xc00029ce60, 0x2, 0x2, 0x0, 0x0, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/gen/gen.go:387 +0x8e5
github.com/filecoin-project/lotus/chain/gen.(*ChainGen).NextTipSet(0xc0006a1450, 0x0, 0x0, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/gen/gen.go:356 +0xdd
github.com/filecoin-project/lotus/chain_test.(*syncTestUtil).repoWithChain(0xc00025b3b0, 0x332d4a0, 0xc00042e900, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/sync_test.go:50 +0x111
github.com/filecoin-project/lotus/chain_test.(*syncTestUtil).addSourceNode(0xc00025b3b0, 0x32)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/sync_test.go:223 +0x17a
github.com/filecoin-project/lotus/chain_test.prepSyncTest(0x332d4a0, 0xc00042e900, 0x32, 0x0)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/sync_test.go:100 +0x3ff
github.com/filecoin-project/lotus/chain_test.TestSyncSimple(0xc00042e900)
	/home/magik6k/github.com/filecoin-project/go-lotus/chain/sync_test.go:363 +0x53
testing.tRunner(0xc00042e900, 0x309a290)
	/usr/lib/go/src/testing/testing.go:991 +0x18a
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1042 +0x660

Debugger finished with exit code 0

```

### CODE REVIEW

**Comment by laser** [comment]
@Kubuxu @magik6k - If you don't want to wait 40 more minutes for me to cut filecoin-ffi 0.3.2, you can replace all calls to `ffi.Aggregate(emptySliceOfSignatures)` with `nil` to avoid this error.

**Comment by laser** [comment]
Example:

```go
func foo(sigs []ffi.Signature) *ffi.Signature {
  if len(sigs) == 0 {
    return nil
  }

  return ffi.Aggregate(sigs)
}
```

**Comment by laser** [comment]
Release 0.30.2 is now live. Please use that release (which includes this bugfix) instead of 0.30.1.

**Comment by magik6k** [comment]
(We're on latest ffi master already)

**Pull request merged**
