### PR TITLE
feat: api: Add API and CLI to unseal sector

### PR DESCRIPTION
**Pull request by shrenujbansal**
## Related Issues

https://github.com/filecoin-project/lotus/issues/5436

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Review by ZenGround0 — COMMENTED** [review]
LGTM

I have a feeling [this TODO](https://github.com/filecoin-project/lotus/blob/master/storage/sealer/manager.go#L374) might now be useful to implement and then create a CLI flag for, maybe in a follow up issue

**Comment by rjan90** [comment]
Worked well on a local devnet, will scale up and do some rounds on 32GiB sectors with real data.

Deal sector in sector 1:
```
lotus-miner sectors list
ID   State    OnChain  Active  Expiration                     Deals  DealWeight  VerifiedPower  
0    Proving  YES      YES     1550097 (in 10 weeks 8 hours)  CC                                
1    Proving  YES      YES     1550097 (in 10 weeks 8 hours)  1      2KiB        18KiB      
```

No unsealed sector:
```
lotus-miner storage find 1
In 94f8a49e-1208-442d-b960-9c6fca5ec2a0 (Sealed, Cache)
        Sealing: true; Storage: true
        Local (/root/.lotus-miner-local-net)
        URL: http://127.0.0.1:2345/remote/sealed/s-t01000-2
```

Then execute: `lotus-miner sectors unseal 1`

```
lotus-miner storage find 1
In 94f8a49e-1208-442d-b960-9c6fca5ec2a0 (Unsealed)
        Sealing: true; Storage: true
        Local (/root/.lotus-miner-local-net)
        URL: http://127.0.0.1:2345/remote/unsealed/s-t01000-1
In cefc9816-79fc-4884-84d4-eb1b6cedf697 (Sealed, Cache)
        Sealing: false; Storage: false
        Local (/root/.genesis-sectors)
        URL: http://127.0.0.1:2345/remote/sealed/s-t01000-1
```

**Comment by shrenujbansal** [comment]
> this TODO

**Comment by shrenujbansal** [comment]
> I have a feeling [this TODO](https://github.com/filecoin-project/lotus/blob/master/storage/sealer/manager.go#L374) might now be useful to implement and then create a CLI flag for, maybe in a follow up issue

@ZenGround0 I think this requires a bit of thought as to where we'd want to move the unsealed sector too. Don't wanna gate this PR on that

**Review by ZenGround0 — APPROVED** [review]

**Pull request merged**
