### PR TITLE
feat: f3: update go-f3 to 0.2.0

### PR DESCRIPTION
**Pull request by Kubuxu**
Includes:
 - fix for excessive bandwidth usage
 - significant performance improvements
 - minor F3 consensus fixes

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [x] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [x] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [x] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Kubuxu** [comment]
:shrug: no idea why it is is still angry

**Comment by Kubuxu** [comment]
That is different than what is in the doc: https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions

**Comment by rvagg** [comment]
@Kubuxu lower-case description .. I'm sure that _was_ in there originally; @rjan90 where did that go in that doc?

**Comment by rjan90** [comment]
> @Kubuxu lower-case description .. I'm sure that was in there originally; @rjan90 where did that go in that doc?

It originally said it in the comment like so: https://github.com/filecoin-project/lotus/pull/12340#pullrequestreview-2218989687 - but we missed brining that over to the https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions. Will add

**Review by rjan90 — APPROVED** [review]

**Comment by Kubuxu** [comment]
@rvagg @rjan90 what threw me for a loop is this in  docs `<type>(<scope>): <description>` while the CI checks for: <type>: <scope>: <description> `

**Pull request merged**
