### PR TITLE
update to markets v1.2.x

### LINKED ISSUE #5133: The file size transferred during the deal is much larger than the actual file size.
**Describe the bug**
The file size transferred during the deal is much larger than the actual file size.

image

```
louts  client list-deals -v 
root@10-8-78-110:/data/deal_scripts# lc list-deals -v
Created          DealCid                                                      DealId   Provider  State                             On Chain?  Slashed?  PieceCID                                                          Size       Price              Duration  Verified  Message
Dec  8 22:16:12  bafyreifwbnnu7tzqccfrmevrwcxnx6ipoctwnzjtefymtiujimvjx7gtym  1436539  f085710   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.000520669 FIL    520669    false
Dec  8 23:25:15  bafyreieo3v6k3qh7p3iig64kbsc5nfupoblfktnthslarhmdq45jhzwjaq  0        f023868   StorageDealCheckForAcceptance     N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.00001041416 FIL  520708    false     Provider state: StorageDealUnknown
Dec  9 10:46:25  bafyreifwgfmm2aq544cgmjjdcwnfqhjvcnmedcdjpogsjvjwzkikblroky  0        f034545   StorageDealClientTransferRestart  N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0 FIL              522043    false
Dec  9 11:58:56  bafyreibhfr2pah3ha26yddngdgv22o4aktafq2ucghizfol6nqqe66a6pu  1439889  f044160   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqicfrhqddzqb33kly4otpymvzfrviiiybe75aibpk5ud2xsoqpmey  1.984 GiB  0.000522358 FIL    522358    false
Dec  9 14:04:19  bafyreiekxxbplgm26xd6onihe3wk7wgrljrzoqjk3foike2na5w2pejto4  1438964  f063869   StorageDealAwaitingPreCommit      N          N         baga6ea4seaqdvheocjffe6nppls2i7yxfvxr52em43xg3drr4i4iknxbxxn2ugq  1.984 GiB  0 FIL              521264    false
Dec  9 17:56:25  bafyreibvi7hjqmtwlb7h35mkkbmvpe2zuntv5n3q72c2nyoddiysq4ffjy  0        f010493   StorageDealCheckForAcceptance     N          N         baga6ea4seaqdvheocjffe6nppls2i7yxfvxr52em43xg3drr4i4iknxbxxn2ugq  1.984 GiB  0.000521296 FIL    521296    false     Provider state: StorageDealReserveProviderFunds
```

### LINKED ISSUE #5443: Retrieval deals shouldn't be queued concurrently when CID/miner match
When a transfer is interrupted or it's not clear that a deal is in-progress, it's common for a human or code to retry.  If there is an existing retrieval deal with the same CID/client-id on the miner that is already in the queue, we should just return that deal-ID rather than creating a new deal.

There is an edge case that the price of the retrieval deal could get cheaper, but the request is that price is ignored.  The previous deal can be canceled if they want to resubmit the request and go to the end of the queue..

### PR DESCRIPTION
**Pull request by dirkmc**
Fixes #5133
Fixes #5443 

Note: This version of markets still contains several known issues with retrieval, that will be fixed in a subsequent release (For example if the connection goes down during a retrieval, the deal will not recover).

Major improvements:
- Detect when client fails to get an Accept or Complete message from miner during storage deal
- Better error reporting when there's an issue with unsealing / reading data from the blockstore
- Don't double count the amount of transferred data when there's a restart during the transfer

For a detailed list of changes, see the changelog in go-fil-markets (from v1.1.9 - v1.2.3):
https://github.com/filecoin-project/go-fil-markets/blob/master/CHANGELOG.md

Tasks:
- [x] Run testground test that makes a deal between lotus client / provider of master / this branch
- [x] Run manual storage and retrieval deal
  - [x] this branch client -> v1.5.3 miner
    - [x] Storage deal
    - [x] Retrieval deal
  - [x] this branch client -> this branch miner
    - [x] Storage deal
    - [x] Storage deal with miner restart
    - [x] Retrieval deal
- [x] Merge https://github.com/filecoin-project/lotus/pull/5851 (nice to have)
- [ ] Merge https://github.com/filecoin-project/lotus/pull/5871 (nice to have)

### CODE REVIEW

**Comment by dirkmc** [comment]
### Testground tests

#### Client (master) <-> Provider (feat/markets-v1.2.0)

https://ci.testground.ipfs.team/logs?task_id=c1ca6od5p7aahco59v2g

```
$ LOTUS_VERSION_CLIENT=master LOTUS_VERSION_MINER=d48dc4f testground run composition -f ./_compositions/baseline-k8s-1-1-versions.toml --metadata-commit=d48dc4f --metadata-repo=filecoin-project/lotus --metadata-branch=feat/markets-v1.2.0

$ kubectl exec -it tg-lotus-soup-c1ca6od5p7aahco59v2g-clients-0 sh
# cat testground_dep_list  | grep lotus
github.com/filecoin-project/lotus/testplans/lotus-soup
github.com/filecoin-project/lotus v1.5.2 => github.com/filecoin-project/lotus v1.5.3-rc1.0.20210319182246-43d9cc36a4ea

$ kubectl exec -it tg-lotus-soup-c1ca6od5p7aahco59v2g-miners-0 sh
# cat testground_dep_list  | grep lotus
github.com/filecoin-project/lotus/testplans/lotus-soup
github.com/filecoin-project/lotus v1.5.2 => github.com/filecoin-project/lotus v1.5.3-rc1.0.20210322110805-d48dc4fc916e
```

#### Client (feat/markets-v1.2.0) <-> Provider (master)

https://ci.testground.ipfs.team/logs?task_id=c1cabnt5p7aahco59v30

```
$ LOTUS_VERSION_CLIENT=d48dc4f LOTUS_VERSION_MINER=master testground run composition -f ./_compositions/baseline-k8s-1-1-versions.toml --metadata-commit=d48dc4f --metadata-repo=filecoin-project/lotus --metadata-branch=feat/markets-v1.2.0


$ kubectl exec -it tg-lotus-soup-c1cabnt5p7aahco59v30-clients-0  sh
# cat testground_dep_list  | grep lotus
github.com/filecoin-project/lotus/testplans/lotus-soup
github.com/filecoin-project/lotus v1.5.2 => github.com/filecoin-project/lotus v1.5.3-rc1.0.20210322110805-d48dc4fc916e

$ kubectl exec -it tg-lotus-soup-c1cabnt5p7aahco59v30-miners-0  sh
# cat testground_dep_list  | grep lotus
github.com/filecoin-project/lotus/testplans/lotus-soup
github.com/filecoin-project/lotus v1.5.2 => github.com/filecoin-project/lotus v1.5.3-rc1.0.20210319182246-43d9cc36a4ea
```

**Comment by dirkmc** [comment]
Manual testing has revealed a couple of issues:
- https://github.com/filecoin-project/go-data-transfer/issues/168
   Merged, needs to be tested again
- https://github.com/filecoin-project/go-data-transfer/issues/172
  A bigger fix is needed. Suggest we disable data-rate monitoring for retrievals until the next release, as there are already known issues with retrieval accounting that need to be addressed: https://github.com/filecoin-project/go-data-transfer/issues/151

**Comment by dirkmc** [comment]
It seems that when the client needs to create a payment channel for retrieval, as soon as the payment channel lane is allocated the deal gets stuck in the `Ongoing` state. Our theory is that the connection to the provider goes down while the provider is waiting for the client to create the payment channel.
We don't believe this is a regression but we would like to do some more testing to be sure.

**Comment by dirkmc** [comment]
Turns out it *is* a regression: https://github.com/filecoin-project/go-fil-markets/issues/517

**Comment by dirkmc** [comment]
After updating to markets v1.2.3 the regression is fixed:

```
lotus client retrieve --miner f01234 bafykbzacedbytx65vf2n2daoallyvtrc52pguqvpmofgehncs6p5tk2qbg7pa myfile                                                                           
> Recv: 0 B, Paid 0 FIL, ClientEventOpen (DealStatusNew)                                                                                                                                                 
> Recv: 0 B, Paid 0 FIL, ClientEventDealProposed (DealStatusWaitForAcceptance)                                                                                                                           
> Recv: 0 B, Paid 0 FIL, ClientEventDealAccepted (DealStatusAccepted)                                                                                                                                    
> Recv: 0 B, Paid 0 FIL, ClientEventPaymentChannelAddingFunds (DealStatusPaymentChannelAddingInitialFunds)                                                                                               
> Recv: 29.72 KiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusPaymentChannelAddingInitialFunds)                                                                                                    
> Recv: 29.72 KiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusPaymentChannelAddingInitialFunds)                                                                                                  
> Recv: 1.029 MiB, Paid 0 FIL, ClientEventBlocksReceived (DealStatusPaymentChannelAddingInitialFunds)                                                                                                    
> Recv: 1.029 MiB, Paid 0 FIL, ClientEventPaymentChannelReady (DealStatusPaymentChannelAllocatingLane)                                                                                                   
> Recv: 1.029 MiB, Paid 0 FIL, ClientEventLaneAllocated (DealStatusOngoing)                                                                                                                              
> Recv: 1.029 MiB, Paid 0 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)                                                                                                                       
> Recv: 1.029 MiB, Paid 0 FIL, ClientEventSendFunds (DealStatusSendFunds)                                                                                                                                
> Recv: 1.029 MiB, Paid 0.000000000002158014 FIL, ClientEventPaymentSent (DealStatusOngoing)                                                                                                             
> Recv: 2.029 MiB, Paid 0.000000000002158014 FIL, ClientEventBlocksReceived (DealStatusOngoing)                                                                                                          
> Recv: 2.029 MiB, Paid 0.000000000002158014 FIL, ClientEventPaymentRequested (DealStatusFundsNeeded)                                                                                                    
> Recv: 3.029 MiB, Paid 0.000000000002158014 FIL, ClientEventBlocksReceived (DealStatusFundsNeeded)                                                                                                      
> Recv: 3.029 MiB, Paid 0.000000000002158014 FIL, ClientEventSendFunds (DealStatusSendFunds)                                                                                                             
> Recv: 3.029 MiB, Paid 0.000000000006352318 FIL, ClientEventPaymentSent (DealStatusOngoing)                                                                                                             
> Recv: 4.029 MiB, Paid 0.000000000006352318 FIL, ClientEventBlocksReceived (DealStatusOngoing)                                                                                                          
...
> Recv: 583 MiB, Paid 0.000000001176563134 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 584 MiB, Paid 0.000000001176563134 FIL, ClientEventBlocksReceived (DealStatusOngoing)
> Recv: 584 MiB, Paid 0.000000001176563134 FIL, ClientEventLastPaymentRequested (DealStatusFundsNeededLastPayment)
> Recv: 584.6 MiB, Paid 0.000000001176563134 FIL, ClientEventBlocksReceived (DealStatusFundsNeededLastPayment)
> Recv: 584.6 MiB, Paid 0.000000001176563134 FIL, ClientEventAllBlocksReceived (DealStatusSendFundsLastPayment)
> Recv: 584.6 MiB, Paid 0.000000001226060862 FIL, ClientEventPaymentSent (DealStatusFinalizing)
> Recv: 584.6 MiB, Paid 0.000000001226060862 FIL, ClientEventComplete (DealStatusCompleted)
Success
```

**Comment by dirkmc** [comment]
I re-ran the testground tests against the latest commit to verify compatibliity between this branch and lotus master:

#### Client (master) <-> Provider (feat/markets-v1.2.0)

https://ci.testground.ipfs.team/logs?task_id=c1ea36t5p7aahco5a0b0

```
$ LOTUS_VERSION_CLIENT=master LOTUS_VERSION_MINER=0134099 testground run composition -f ./_compositions/baseline-k8s-1-1-versions.toml --metadata-commit=0134099 --metadata-repo=filecoin-project/lotus --metadata-branch=feat/markets-v1.2.0
```

#### Client (feat/markets-v1.2.0) <-> Provider (master)

https://ci.testground.ipfs.team/logs?task_id=c1ea3255p7aahco5a0ag

```
LOTUS_VERSION_CLIENT=0134099 LOTUS_VERSION_MINER=master testground run composition -f ./_compositions/baseline-k8s-1-1-versions.toml --metadata-commit=0134099 --metadata-repo=filecoin-project/lotus --metadata-branch=feat/markets-v1.2.0
```

**Comment by raulk** [comment]
This has been squashed into https://github.com/filecoin-project/lotus/tree/minerx/staging for minerX early testing.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
