### PR TITLE
misc: dockerfile: remove curio from lotus Dockerfile/Makefile

### PR DESCRIPTION
**Pull request by jennijuju**
some part of https://github.com/filecoin-project/lotus/issues/12051

### CODE REVIEW

**Review by LexLuthr — CHANGES_REQUESTED** [review]
We should probably remove sptool as well. 
https://github.com/filecoin-project/lotus/pull/12042/files removes that one as well.

**Comment by jennijuju** [comment]
> We should probably remove sptool as well. https://github.com/filecoin-project/lotus/pull/12042/files removes that one as well.

No i dont think we can, as lotus miner users are still relying on them. We should keep the clis needed by lotus miner users until curio team also moves lotus miner to curio repo (assuming curio team will be the maintainer of lotus miner)

**Comment by jennijuju** [comment]
> `sptool` has nothing to do with lotus-miner. All `lotus-miner` command should work without it.

are you sure @LexLuthr  - https://github.com/filecoin-project/lotus/pull/11788/files#diff-838b636b2eec0cf90b98faa2695b5cc10ce0563fae855049d4ac089b090cca76 seems like removing the cli from lotus miner and moving to sptool

**Comment by LexLuthr** [comment]
I think you might be confusing `cli/sptool` with `cmd/sptool`. All the actual shared code for sptool/miner lives under `cli/sptoo`l. The `cmd/sptool` is just the command wrapper.

**Comment by jennijuju** [comment]
> I think you might be confusing `cli/sptool` with `cmd/sptool`. All the actual shared code for sptool/miner lives under `cli/sptoo`l. The `cmd/sptool` is just the command wrapper.

i see, thanks

**Review by LexLuthr — APPROVED** [review]
Looks good now

**Comment by rjan90** [comment]
Closing since these changes have already been merged/included with: https://github.com/filecoin-project/lotus/pull/12042

**Pull request closed without merging**
