### PR TITLE
Add tests for api depending on ffi

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by Kubuxu** [comment]
Currently it fails because:
```
> depth -explain github.com/filecoin-project/filecoin-ffi .                   
. -> github.com/filecoin-project/lotus/chain/store -> github.com/filecoin-project/lotus/chain/vm -> github.com/filecoin-project/sector-storage/ffiwrapper -> github.com/filecoin-project/filecoin-ffi
. -> github.com/filecoin-project/sector-storage -> github.com/filecoin-project/filecoin-ffi
```

**Comment by whyrusleeping** [comment]
I love it

**Comment by whyrusleeping** [comment]
Looks like store.HeadChange and sectorstore.WorkerStats are the culprits

we should just duplicate these types and move on

**Comment by jsign** [comment]
Nice PR!
I'm maintaining `github.com/textileio/lotus-client` which is solving this problem for the client API. The solution there is simple:
- Delete some 2 o 3 APIs with some problematic structs
- On some other APIs I'm interested in, I copy-pasted a narrowed down files of the struct with only the necessary. Avoiding big packages that lead to a filecoin-ffi path.
- The problematic things where `store` and `vm` package... so that's aligned with @Kubuxu conclusions.

That repo was meant to be temporal and eventually try to do what this PR intends, so this is great.

Some extra point that might be interesting to add to this check, is checking that `lib/jsonrpc` is also filecoin-ffi free. That *is* the case now, so isn't a problem... but would be nice to get that covered just in case. That package has much less risk to become tangled with filecoin-ffi, so might not worth it.

**Comment by whyrusleeping** [comment]
@jsign We're actually pretty likely to extract the jsonrpc package to its own repo anyways, it has no filecoin dependencies at all, extremely unlikely to gain one on the ffi 

In any case, i think this is ready! We have killed the ffi dependence! (Now to make sure we make it to our 'FFI Importers Anonymous' meetings)

**Pull request merged**
