### PR TITLE
vm: check aborted error code from actor

### PR DESCRIPTION
**Pull request by nonsense**
This PR is an attempt to address the failures in this test: `Test that an actor cannot Abort with a system exit code` - https://github.com/filecoin-project/test-vectors/issues/15

At the moment it appears that the VM runtime is propagating back the error codes that actors abort with, and it seems like this is not what we want. cc @anorth  

---

Related: https://github.com/filecoin-project/test-vectors/pull/49

### CODE REVIEW

**Comment by Kubuxu** [comment]
This won't work as we pass both actor and system errors through this.

**Comment by nonsense** [comment]
> This won't work as we pass both actor and system errors through this.

You mean that this recover is catching panic both from `actors` and from the VM runtime? If that's the case, I understand what you mean, and why this PR is wrong.

**Comment by Kubuxu** [comment]
Yes, for example:
`SysErrOutOfGas` can be triggered in internal `Send` then it will be caught by this.

**Comment by anorth** [comment]
@nonsense I think you need to make the check as the first thing inside the implementation of the `Runtime.Abort()` that the actor code calls.

**Comment by nonsense** [comment]
@alanshaw did this properly at https://github.com/filecoin-project/lotus/pull/3656

**Pull request closed without merging**
