### PR TITLE
Always flush when timer goes off

### LINKED ISSUE #6541: Send commits using ProveCommitSectors when time configs hit
when [cfg.CommitBatchWait is hit and # of sector is < minbatch ](https://github.com/filecoin-project/lotus/blob/715176698ffa1ac089963765d65a2dd355364114/extern/storage-sealing/commit_batch.go#L193-L195)we are doing nothing, but we should  processIndividually in this case to send the commits out

### PR DESCRIPTION
**Pull request by arajasek**
Might add a test, but here's a PR.

Fixes #6541

### CODE REVIEW

**Review by magik6k — APPROVED** [review]

**Comment by BigLep** [comment]
Is there a reason we wouldn't add a test here?

**Comment by jennijuju** [comment]
I think the same logic change should be applied to pre commit batcher too.

**Review by jennijuju — CHANGES_REQUESTED** [review]
I think the same logic change should be applied to pre commit batcher too.

**Comment by magik6k** [comment]
> I think the same logic change should be applied to pre commit batcher too.

In the precommit batcher the min batch size has a slightly different meaning as we haven't committed to publishing those sectors yet, and sending individual precommits makes no sense, so the only use for MinBatch is not sending anything

We might want to have Commit / PreCommitMinBatch config vars have different names tho, to make sure it's clear that they are doing quite different things

**Comment by arajasek** [comment]
> > I think the same logic change should be applied to pre commit batcher too.
> 
> In the precommit batcher the min batch size has a slightly different meaning as we haven't committed to publishing those sectors yet, and sending individual precommits makes no sense, so the only use for MinBatch is not sending anything
> 
> We might want to have Commit / PreCommitMinBatch config vars have different names tho, to make sure it's clear that they are doing quite different things

Aren't there two cases when we _do_ want to publish sectors, though:

- if a ticket is expiring (and we're risking losing the PC work)
- if a deal included in the sector is approaching activation

**Comment by arajasek** [comment]
Summary: makes sense to just remove MinPreCommitBatch entirely -- if the timer goes off, we just batch and precommit whatever we have.

Thanks @jennijuju!

**Review by magik6k — APPROVED** [review]

**Pull request merged**
