### PR TITLE
build: backport changes to `release/v1.30.0` branch

### PR DESCRIPTION
**Pull request by rjan90**
## Related Issues
https://github.com/filecoin-project/lotus/issues/12480

## Proposed Changes
Backports PRs that has landed with a backport label on them to the `release/v1.30.0`: https://github.com/filecoin-project/lotus/pulls?q=is%3Apr+label%3Arelease%2Fbackport+is%3Aclosed, to the releases branch.

PRs in question:

- [x] https://github.com/filecoin-project/lotus/pull/12597
- [x] https://github.com/filecoin-project/lotus/pull/12608
- [x] https://github.com/filecoin-project/lotus/pull/12615
- [x] https://github.com/filecoin-project/lotus/pull/12620
- [x] https://github.com/filecoin-project/lotus/pull/12621
- [x] https://github.com/filecoin-project/lotus/pull/12627
- [x] https://github.com/filecoin-project/lotus/pull/12634
- [x] https://github.com/filecoin-project/lotus/pull/12637
- [x] https://github.com/filecoin-project/lotus/pull/12640
- [x] https://github.com/filecoin-project/lotus/pull/12641
- [x] https://github.com/filecoin-project/lotus/pull/12648
- [x] https://github.com/filecoin-project/lotus/pull/12649
- [x] https://github.com/filecoin-project/lotus/pull/12647
- [x] https://github.com/filecoin-project/lotus/pull/12647

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [x] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [x] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [x] CI is green

### CODE REVIEW

**Comment by rjan90** [comment]
@masih / @Kubuxu let us discuss if we want to ship a Lotus v1.30.0-rc3 with these backports so we can run some testing with these changes before shipping a final release on `2024-10-28`

**Comment by masih** [comment]
Can we also get [this](https://github.com/filecoin-project/lotus/pull/12637) in when merged please?

**Comment by masih** [comment]
And [this](https://github.com/filecoin-project/lotus/pull/12627) please

**Comment by masih** [comment]
We also need the fix for [this](https://github.com/filecoin-project/go-f3/issues/719) in lotus

**Comment by rjan90** [comment]
> Can we also get https://github.com/filecoin-project/lotus/pull/12637 in when merged please?
> And https://github.com/filecoin-project/lotus/pull/12627 please
> We also need the fix for https://github.com/filecoin-project/go-f3/issues/719 in lotus

Yeah, I will wait for those to land and adding those to this backport.

**Comment by rjan90** [comment]
@masih all PRs with a `backport` label has now been added to this PR. I´m failing to complete the `make gen` to make that check green, because it fails here:

> go build  -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.d3b014faf" -o lotus ./cmd/lotus
> # github.com/zondax/hid
> vendor/github.com/zondax/hid/hid_enabled.go:39:11: fatal error: 'hidapi/mac/hid.c' file not found
>         #include "hidapi/mac/hid.c"
>                  ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [lotus] Error 1

And I can´t see that I´m touching anything with regards to that here. Could you maybe help me out with that?

**Comment by rjan90** [comment]
> I am not sure about the fatal error: 'hidapi/mac/hid.c' file not found you are observing. It runs on my machine. re-generation pushed.

Hmmmm.. I will have to do some fixing on my end it seems, `go mod tidy` did not sort it, but good that it runs on your machine.

**Review by Kubuxu — APPROVED** [review]
SGWM we just need https://github.com/filecoin-project/lotus/pull/12650 for rc3

**Review by masih — APPROVED** [review]

**Pull request merged**
