### PR TITLE
[skip changelog] chore: tests: fix failures on recent macos

### PR DESCRIPTION
**Pull request by ribasushi**
On modern darwin `os.ReadDir("/dev/fd")` always results in an error. Because of this storage/sealer/ffiwrapper/sealer_test.go invariably fails.

Instead of fixing the FD enumerator, remove the check entirely, as it has been disabled since https://github.com/filecoin-project/lotus/pull/7420/files

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
heh, ok, we lose some logging here and also some nagging

@vmx should we expect any leaky fds? do you think this check might be ancient and irrelevant enough that complete removal is reasonable?

**Comment by rvagg** [comment]
Yeah, the main thing about removing the logging for me is the loss of instutional knowledge that this _could be a problem_. With this code gone, I'm unaware that this ever is/was a thing. What I'd like to know is if this is a real problem now, or just historical baggage we can happily forget.

**Review by magik6k — APPROVED** [review]
This code has served it's purpose a long time ago when this was a problem

**Comment by rvagg** [comment]
👌 thanks @magik6k

**Pull request merged**
