### PR TITLE
fix `lotus-miner storage-deals set-ask` - make sure that `ActorAddress` works on all miner nodes

### PR DESCRIPTION
**Pull request by nonsense**
This PR is fixing https://github.com/filecoin-project/lotus/issues/6921

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
I'd expect `ActorAddress` to work on the market node, with that we can call the full node for sector size -> `StateMinerInfo().SectorSize`

**Comment by nonsense** [comment]
@raulk @magik6k given that we discussed that this is an immutable value, I think this is good solution. You okay with it, or you have something else in mind?

**Review by raulk — COMMENTED** [review]
Honestly I'm not comfortable doing this. The reason why this works is because it's a side-effect from having copied the miner's metadata store into the markets process. I'm not even sure that was the right thing to do in the first place, and if we merge this, we will be marrying to that approach forever.

**Review by raulk — COMMENTED** [review]
This is already solved by https://github.com/filecoin-project/lotus/pull/6936, as CLI commands are now intelligent to route to the miner node or the markets node. I don't see the need to merge a miner-side change.

**Comment by jacobheun** [comment]
Closing as this is no longer needed with #6936.

**Pull request closed without merging**
