### PR TITLE
fix: Eth JSON-RPC api: handle messages with gasFeeCap less than baseFee

### PR DESCRIPTION
**Pull request by ychiaoli18**
## Related Issues
https://github.com/filecoin-project/lotus/issues/10604

## Proposed Changes
Use 0 as reward if gasFeeCap is less than baseFee

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Review by raulk — COMMENTED** [review]
I'd push the filtering logic into the calculate* function so we still return the correct gas utilisation ratio, and only disregard the negative data point for percentile calculation.

**Review by Stebalien — APPROVED** [review]
Can we update the comment to note that this value is clamped at 0 as well?

**Comment by Stebalien** [comment]
Also note, we don't use this method anywhere _except_ the Eth API.

**Comment by maciejwitowski** [comment]
@ychiaoli18 @Stebalien Can we merge this PR?

**Pull request merged**
