### PR TITLE
Fix panic in FundManager

### PR DESCRIPTION
**Pull request by dirkmc**

### CODE REVIEW

**Comment by jsign** [comment]
I can confirm that the pipeline I ran to discover this stopped panicking, so looks good.

**Review by hannahhoward — APPROVED** [review]
I am a bit anxious about the sequence of things that gets us to this condition -- how would we end up with a reserved > available but no toAdd messages? Worth possible further investigation. That said, no panic is better than panic.

**Review by arajasek — APPROVED** [review]
Makes sense

**Comment by dirkmc** [comment]
Update the description with a scenario in which this panic can occur

**Pull request merged**
