### PR TITLE
chore: f3: Upgrade go mod F3 dependency to v0.0.3 tagged release

### PR DESCRIPTION
**Pull request by masih**
## Related Issues
N/A

## Proposed Changes
Use concrete/latest version of F3: v0.0.3

## Additional Info
None.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] Update CHANGELOG.md or signal that this change does not need it.
  - If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
  - If the change does not require a CHANGELOG.md entry, do one of the following:
    - Add `[skip changelog]` to the PR title
    - Add the label `skip/changelog` to the PR
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Kubuxu** [comment]
@masih sorry for the mess, I decided to fix it right the same moment you did. I pushed your commit back.

**Review by Kubuxu — APPROVED** [review]

**Comment by masih** [comment]
> @masih sorry for the mess, I decided to fix it right the same moment you did. I pushed your commit back.

No worries; thanks Kuba!

**Comment by rjan90** [comment]
Removing the `release/backport` label from this PR, as it is obsoleted by this PR: https://github.com/filecoin-project/lotus/pull/12237 which also carries the `release/backport` label

**Comment by Kubuxu** [comment]
@rjan90 feel free to apply this code change manually as it is quite minimal

**Pull request merged**
