### PR TITLE
ClientFindData: always fetch peer id from chain

### PR DESCRIPTION
**Pull request by nonsense**
This PR is fixing `ClientFindData` when data about peers in the local store of a node is out-dated.

---

If a client makes a deal with a miner, it keeps the miner's peer id in a local store. In the future if the miner changes its peer id, and the client tries to retrieve the content (datacid), `ClientFindData` would still be trying to reach the miner on its old peer id, ultimately failing.

This is manifested with `Failed to find file` error in the CLI:

```
➜  lotus git:(master) lotus client retrieve $datacid /tmp/file1234
Failed to find file
```

### CODE REVIEW

**Review by dirkmc — APPROVED** [review]
LGTM 👍

**Review by Kubuxu — APPROVED** [review]

**Review by raulk — APPROVED** [review]

**Review by raulk — APPROVED** [review]
Can we have a test for this in this PR, or an issue to track? 🙏

**Review by magik6k — APPROVED** [review]

**Comment by BigLep** [comment]
@nonsense : did the test get added?

**Comment by nonsense** [comment]
@BigLep I don't think there is a test for this case.

We will have one as soon as we finish the lotus-compatibility tests part of M1 (initial PR at https://github.com/filecoin-project/lotus/pull/6765 )

**Comment by BigLep** [comment]
Beautiful - thanks.

**Pull request merged**
