### PR TITLE
lotus v1.27.2-rc2

### PR DESCRIPTION
**Pull request by rvagg**
Let's try out the auto-release builder again.

### CODE REVIEW

**Comment by galargh** [comment]
There's one more thing. We have https://github.com/filecoin-project/lotus/settings/rules/575504 set up which restricts who can create tags. In particular, it's going to block creation of a tag on release publish when we merge this PR because we're using the default GitHub token. To overcome this we can:
a. disable the tag creation rule
b. use PAT belonging to eligible user for publishing the releases

For this release, we can either go with a. temporarily or do the publish release step manually after the merge and after the release workflow from the merge finishes/fails (the publish is the last step and nothing else happens after it so if it fail it's OK if we do just that one ourselves). And, in the meantime, I'll set up b. so that we don't have to disable the protection rule.

**Comment by rvagg** [comment]
@galargh is there no way to add GHA to the "bypass" list? That seems like an oversight.

**Comment by galargh** [comment]
Unfortunately, no. The reason they give is that it would allow anyone with push access to bypass the rules. I still think it would be beneficial to have that option since it would allow preventing accidental tag creations.

Anyway, I now set up TAG_CREATE_GITHUB_TOKEN secret and updated the ipdx/release-automation branch so that it uses it.

**Review by aarshkshah1992 — APPROVED** [review]

**Comment by galargh** [comment]
https://github.com/filecoin-project/lotus/releases/tag/v1.27.2-rc2 was created by https://github.com/filecoin-project/lotus/actions/runs/9940753120 as expected

Then, docker publish was triggered by the tag creation (which is another reason why we need to use a PAT for publish, really) - https://github.com/filecoin-project/lotus/actions/runs/9941688486

**Pull request merged**
