### PR TITLE
Splitstore optimizations

### PR DESCRIPTION
**Pull request by vyzo**
This optimizes the splitstore so that
- we get rid of the full compaction option, as it is not exercised or terribly useful. It was written with an eye to gc, but that one is dangerous.
- we use an optimized version of chain walking that doesn't walk the entire chain and only visits state roots; this keeps the hotstore size effectively constant, instead of slowly growing as it the chain grows.
- we mark from the current epoch to the boundary epoch when we detect sync gaps, in order to avoid pathologies if the node stays offline for an extended period of time.
- we reduce the CompactionThreshold to 3 finalities; that means that we retain only 2-3 finalities in the hot range, reducing the size of the hotstore by 40% (50% right after a compaction).

Also adds a lotus-shed command for aggressive offline gc.

See #5789 

The new chain walking warms up the splitstore 3x faster, while it makes marking 4x faster.

### CODE REVIEW

**Comment by vyzo** [comment]
cc @travisperson

**Comment by vyzo** [comment]
Compaction timings:
```
2021-03-15T10:50:30.289Z        INFO    splitstore      splitstore/splitstore.go:459    compacting splitstore
2021-03-15T10:50:30.289Z        INFO    splitstore      splitstore/splitstore.go:578    current mark set size estimate  {"size": 28905378}
2021-03-15T10:50:30.289Z        INFO    splitstore      splitstore/splitstore.go:614    running compaction      {"currentEpoch": "583301", "baseEpoch": "580600", "coldEpoch": "581500", "boundaryEpoch": "581501"}
2021-03-15T10:50:30.297Z        INFO    splitstore      splitstore/splitstore.go:623    marking reachable blocks        {"currentEpoch": "583301", "boundaryEpoch": "581501"}
2021-03-15T10:55:19.569Z        INFO    splitstore      splitstore/splitstore.go:661    marking done    {"took": 289.272758041, "marked": 5341615}
2021-03-15T10:55:19.569Z        INFO    splitstore      splitstore/splitstore.go:664    collecting cold objects
2021-03-15T10:55:34.133Z        INFO    splitstore      splitstore/splitstore.go:706    collection done {"took": 14.563356311}
2021-03-15T10:55:34.133Z        INFO    splitstore      splitstore/splitstore.go:707    compaction stats        {"hot": 24675484, "cold": 9769333}
2021-03-15T10:55:34.133Z        INFO    splitstore      splitstore/splitstore.go:722    moving cold blocks to the coldstore
2021-03-15T11:01:49.851Z        INFO    splitstore      splitstore/splitstore.go:728    moving done     {"took": 375.718115804}
2021-03-15T11:01:49.851Z        INFO    splitstore      splitstore/splitstore.go:731    purging cold objects from the hotstore
2021-03-15T11:02:15.783Z        INFO    splitstore      splitstore/splitstore.go:737    purging cold from hotstore done {"took": 25.93228677}
2021-03-15T11:02:15.783Z        INFO    splitstore      splitstore/splitstore.go:741    purging cold objects from tracker
2021-03-15T11:02:39.395Z        INFO    splitstore      splitstore/splitstore.go:746    purging cold from tracker done  {"took": 23.611774287}
2021-03-15T11:02:39.629Z        INFO    splitstore      splitstore/splitstore.go:935    compacting hotstore
2021-03-15T11:02:53.248Z        INFO    splitstore      splitstore/splitstore.go:941    hotstore compaction done        {"took": 13.618448949}
2021-03-15T11:02:53.248Z        INFO    splitstore      splitstore/splitstore.go:948    garbage collecting hotstore
2021-03-15T11:03:53.860Z        INFO    splitstore      splitstore/splitstore.go:954    hotstore garbage collection done        {"took": 60.612840167}
2021-03-15T11:03:53.861Z        INFO    splitstore      splitstore/splitstore.go:464    compaction done {"took": 803.572029552}
```

Disk space usage:
```
# du --si ~/.lotus/
8.2k    /root/.lotus/keystore
82G     /root/.lotus/datastore/chain
17k     /root/.lotus/datastore/staging
17k     /root/.lotus/datastore/client
1.9M    /root/.lotus/datastore/metadata
45G     /root/.lotus/datastore/splitstore/hot.badger
48G     /root/.lotus/datastore/splitstore
130G    /root/.lotus/datastore
16M     /root/.lotus/journal
0       /root/.lotus/heapprof
17M     /root/.lotus/kvlog/metadata
17M     /root/.lotus/kvlog
0       /root/.lotus/data-transfer
130G    /root/.lotus/
```

**Comment by vyzo** [comment]
rebased on master.

**Comment by arajasek** [comment]
Will this include https://github.com/filecoin-project/lotus/issues/5057?

**Comment by vyzo** [comment]
no, it's out of scope.

**Comment by vyzo** [comment]
rebased on master and resolved the conflict.

**Comment by vyzo** [comment]
subsumed by #6474

**Pull request closed without merging**
