### PR TITLE
feat: curio: docker devnet

### PR DESCRIPTION
**Pull request by LexLuthr**
## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by LexLuthr** [comment]
@Reiers Can you test this?

**Comment by snadrus** [comment]
Per his testing, it looks very good, but it requires SUDO because of places that it writes to. 
Can we avoid the need for sudo?

**Comment by LexLuthr** [comment]
@snadrus @reiers I am using this on a MaC without sudo. Can you confirm your OS? It writes to local home directory and should not require Sudo.

**Comment by LexLuthr** [comment]
@snadrus Just confirmed, we don't need sudo https://github.com/filecoin-project/lotus-docs/pull/727#issuecomment-2098024958

**Review by magik6k — APPROVED** [review]
Really cool

**Review by magik6k — APPROVED** [review]

**Pull request merged**
