### PR TITLE
deps: update go-libp2p@v0.19

### PR DESCRIPTION
**Pull request by vyzo**
libp2p v0.19 has been released

### CODE REVIEW

**Comment by jennijuju** [comment]
Ci  is sad + please follow the pr title format mentioned in pr template !

**Comment by vyzo** [comment]
CI is sad because of go version; waiting for https://github.com/filecoin-project/lotus/pull/8512

**Comment by vyzo** [comment]
the lint failure is an artifact of the new linter version; i think we should ignore it in this pr and fix it in a separate one.

**Comment by jennijuju** [comment]
@vyzo lets fix it in this PR as it introduces it? (the later PRs aren't facing this failure.

**Comment by vyzo** [comment]
yes, just needs rebase

**Comment by jennijuju** [comment]
> yes, just needs rebase

rebased happy lint

**Review by jennijuju — APPROVED** [review]

**Pull request merged**
