### PR TITLE
Check for correct nonce before taking gas

### PR DESCRIPTION
**Pull request by Kubuxu**
Otherwise as a miner you are able to include an invalid message forever
and get whole GasLimit of gas from it every time.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Kubuxu this LGTM, but does it match the spec? We might have some updating to do there

**Comment by whyrusleeping** [comment]
( I can handle the updating if necessary)

**Comment by Kubuxu** [comment]
IDK where in spec to look.

**Comment by whyrusleeping** [comment]
@Kubuxu no worries, i'll look for it. no reason to block merging now though

**Pull request merged**
