### PR TITLE
Robust message management 

### PR DESCRIPTION
**Pull request by vyzo**
Closes https://github.com/filecoin-project/lotus/issues/5869.

This is the staging branch for the robust message management epic undertaken by @Kubuxu and @vyzo (with cameo appearances by @raulk).

PRs:
- [X] https://github.com/filecoin-project/lotus/pull/5767
- [X] https://github.com/filecoin-project/lotus/pull/5803

### CODE REVIEW

**Comment by Kubuxu** [comment]
TODO:
- [ ] migrate to v1 API after it is merged
- [ ] fix lite mode issues with getting nonce for checks

**Comment by Kubuxu** [comment]
@magik6k @arajasek initial review would be welcome.

**Comment by Kubuxu** [comment]
Re-requesting initial review. @magik6k @arajasek 
The Lotus Lite  test failure is most likely related to https://github.com/filecoin-project/lotus/issues/5995

**Comment by jennijuju** [comment]
@Kubuxu could you please add a feature to handle miner creation messages?

**Comment by jennijuju** [comment]
blocked by v1 api

**Comment by jennijuju** [comment]
please have the doc ready before landing in master. https://github.com/filecoin-project/filecoin-docs/issues/822

**Comment by arajasek** [comment]
Squinted at the message checking logic, and SGWM. FISITIP.

**Pull request merged**
