### PR TITLE
fix message list api

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by Kubuxu** [comment]
Doc gen.

**Comment by Kubuxu** [comment]
also a bit API breaking

**Comment by whyrusleeping** [comment]
@Kubuxu it doesnt actually break the API

**Review by magik6k — APPROVED** [review]

**Comment by Kubuxu** [comment]
I guess not breaking because you shouldn't send full message to that API.

**Review by Kubuxu — APPROVED** [review]

**Comment by mostcute** [comment]
Hello, guys. I started a new node with a snapshot import, then i want to run list-messages api. it print some messages and then break with `blockstore: block not found` . I guess it is because sanpshot  don't have all messages. so how to make a node which start with a snapshot to sync all message agian?

**Comment by mostcute** [comment]
@whyrusleeping @magik6k

**Pull request merged**
