### PR TITLE
chore(f3): update go-f3 to 0.4.0

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Review by masih — APPROVED** [review]
This looks fine 👍 

My vote would be to cut a release in F3 before merging and bubble it up

**Comment by BigLep** [comment]
> My vote would be to cut a release in F3 before merging and bubble it up

Agreed - lets do it right.  We're going to get enforcement of only having released versions in Lotus dependency tree when https://github.com/filecoin-project/lotus/issues/7131 gets done.  Before we have it, it would be good for maintainers to comply :).

**Comment by Stebalien** [comment]
Updated, but now I need to figure out why the itest is failing.

**Comment by Stebalien** [comment]
> Updated, but now I need to figure out why the itest is failing.

Didn't set the catch-up alignment so it defaulted to 1 instance per 15s (way too slow).

**Comment by Stebalien** [comment]
Hm. I got an interesting failure locally: PauseAndRebootstrap failed with:

```
2024-10-03T10:52:24.052-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1001, "instance": 4, "round": 0, "phase": "QUALITY"}
2024-10-03T10:52:24.052-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1002, "instance": 4, "round": 0, "phase": "QUALITY"}
2024-10-03T10:52:24.052-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1000, "instance": 4, "round": 0, "phase": "QUALITY"}
2024-10-03T10:52:24.052-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1003, "instance": 4, "round": 0, "phase": "QUALITY"}
2024-10-03T10:52:24.093-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1001, "instance": 4, "round": 0, "phase": "PREPARE"}
2024-10-03T10:52:24.093-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1000, "instance": 4, "round": 0, "phase": "PREPARE"}
2024-10-03T10:52:24.093-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1002, "instance": 4, "round": 0, "phase": "PREPARE"}
2024-10-03T10:52:24.094-0700    WARN    f3      go-f3@v0.4.0/equivocation.go:87 local self-equivocation detected     {"sender": 1003, "instance": 4, "round": 0, "phase": "PREPARE"}
```

I'm guessing it's because we stopped/restarted? This'll probably be fixed by the WAL integration.

**Comment by Kubuxu** [comment]
SGTM

**Pull request merged**
