### PR TITLE
move DI stuff for paychmgr into modules

### PR DESCRIPTION
**Pull request by whyrusleeping**
This makes it easier to use the paychmgr package outside of lotus.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Review by Stebalien — APPROVED** [review]

**Comment by whyrusleeping** [comment]
I need one or two more things here... the paych manager thing still depends on some funky fx nonsense.  manageAPIImpl is an unexported struct that requires an embedded other type thats fulfilled via the constructor with a magic fx.In PaychAPI *struct* (not interface).

This needs some untangling...

**Comment by whyrusleeping** [comment]
@magik6k youre gonna have to take a look at that last commit, I dont think I really understand what I was doing there with the dependency injection.

**Comment by magik6k** [comment]
Just needed to use the magic `From`, the difference it makes is that if you pass a non-function value as the second param to `Override`, it just gets put into the DI container.

The `From` will instead wrap it into a function returning the value, so it is pulled from DI (`From(*T) -> func(t T) T {return t}`) - which in case of structs with `fx.In` means that all the fields internal to the struct will get pulled from DI (and without the `From` they will just be nil)

(This should be better documented)

**Review by magik6k — APPROVED** [review]

**Comment by whyrusleeping** [comment]
Aha! that makes sense, thanks :)

**Pull request merged**
