### PR TITLE
feat: add API methods to get allocations and claims

### PR DESCRIPTION
**Pull request by geoff-vball**
## Related Issues
Integrates https://github.com/filecoin-project/go-state-types/pull/88 into lotus

## Proposed Changes
Adds 3 new API methods:
Add `StateGetAllocations` to return a map of all allocations for a given client.
Add `StateGetClaims` to return a map of all claims for a given provider.
Add `StateGetClaim` to return a claim given a provider and ClaimId

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

### CODE REVIEW

**Comment by geoff-vball** [comment]
The API methods for `StateGetClaim` and `StateGetAllocation` aren't strictly necessary. We could always return the map and let the client access the ID they want themselves, but would be a fair bit less efficient.

**Comment by jennijuju** [comment]
@arajasek @geoff-vball can you help me understand why this got prioritized? i.e: does this make further changes easier later? I want to understand if this is needed for development, why we did not capture it in the initial issue creation.

**Comment by geoff-vball** [comment]
@jennijuju `StateGetAllocation` was necessary for dealpacking (it's already included in the big PR). These were very quick and easy to add after that and allow us to test the new verifreg functionality if we want.

**Comment by jennijuju** [comment]
nice!

**Review by arajasek — APPROVED** [review]

**Pull request merged**
