### PR TITLE
add a command for compacting sector numbers bitfield

### PR DESCRIPTION
**Pull request by whyrusleeping**
still in progress, would love it if someone could finish this up for me.

### CODE REVIEW

**Comment by Stebalien** [comment]
So, I think the right approach here would be to:

1. Set a target size (no idea what this should be).
2. When we hit twice that size, compact to that size.

The compaction algorithm is actually pretty simple: be greedy.

1. Expand the bitfield into runs of 0s: `(offset, length)`.
2. Sort the runs by length.
3. Starting at the shortest run of 0s, turn that run of 0s into a run of 1s in the original bitfield.

This is optimal (mostly) because it (a) removes two runs for each step and (b) allocates the least sector numbers when doing this.

This is mostly (optimal) because it doesn't account for the cost of encoding a run. Smaller runs are cheeper to encode than larger ones. However, I don't think this matters in practice.

---

I'm happy to take this on, but I'm not sure what the target size should be.

**Comment by Kubuxu** [comment]
For now, I wrote a manual version. The issue being that we need to know which sectors are still being commited, which are abandonned and so on.
Also if we do anything automatic, then we should alert big miners with a lot of sectors.

but the algorithm you are speaking of could be used as `--mask-auto=N` or something like that

**Comment by Stebalien** [comment]
This may be a case for https://rachelbythebay.com/w/2020/10/26/num/. Where, ideally, the number you type in is the number of sector IDs remaining.

**Comment by Kubuxu** [comment]
I would say the number would be a number of sectors that will be marked as unavaliable by the operation. (the bigger the number, the more risk/harm there is).

**Comment by Stebalien** [comment]
Also works. I just want miners to understand that there's a tradeoff.

**Review by magik6k — APPROVED** [review]
Looks landable, but probably should get another approval first

**Review by Kubuxu — APPROVED** [review]

**Pull request merged**
