### PR TITLE
fix method:InitActorState.AddActor

### PR DESCRIPTION
**Pull request by waynewyang**
I think NextID++ should be exec when AddActor success.

### CODE REVIEW

**Comment by waynewyang** [comment]
> This is slightly cleaner to read through logically, but its actually not any different. If any error were to happen, all state changes get reverted, so it doesnt really matter where the variables get incremented.

Thanks,understand!

**Comment by Kubuxu** [comment]
>  all state changes get reverted, so it doesnt really matter where the variables get incremented

@whyrusleeping so with our current architecture this might get weird if MultiSig actor calls these methods.

**Comment by whyrusleeping** [comment]
@Kubuxu how? I don't think it changes at all

**Comment by Kubuxu** [comment]
Ahh, right. The state won't be updated (it will be only updated at the end of succesful execution).

**Pull request merged**
