### PR TITLE
chore: Bump version in master

### PR DESCRIPTION
**Pull request by rjan90**
## Proposed Changes
- Bump version in master now that Lotus v1.26.0-rc1 is out
- Make gen & make docsgen-cli

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
Don't we need to merge master first?

**Comment by Stebalien** [comment]
Sorry, merge the release into master?

**Comment by rjan90** [comment]
> Sorry, merge the release into master?

Yeah, that is next on my checklist. Happy let this PR to wait until that has landed for correctness.

**Comment by Stebalien** [comment]
I'd do that first. I want to be able to say "vN+ supports the upgrade" and not get any confused bug reports from people running master (i.e., me).

**Comment by rjan90** [comment]
Closing, as I´m brining in these changes with https://github.com/filecoin-project/lotus/pull/11699/commits/a613651b3bf49e456d9e4a7381157b7409e9022c in the `merge nv22 into master` PR #11699

**Pull request closed without merging**
