### PR TITLE
Merge/rebased v23 into v22

### PR DESCRIPTION
**Pull request by ZenGround0**
## Proposed Changes

The branch being merged here started its life == release/v1.22.0
Then I rebased this branch on top of release/v1.21.0
Then I merged it back into release/v1.22.0

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
I'm concerned that the rebase may cause merge issues. Did you consider:

1. Forking 1.23 off of 1.21.
2. Merging 1.22 into 1.23.

**Comment by rjan90** [comment]
We should bump the versio in build/version.go, and run the `make docsgen` and `make docsgen-cli`. The gen-check seems to fail because of some merge conflicts

**Comment by Stebalien** [comment]
The diff there is also significantly easier to review.

**Comment by ZenGround0** [comment]
> Forking 1.23 off of 1.21.

I don't have branch permissions or the ability to set them and I woke up to this branch set at 1.22.  If you have branch permissions and can do hard reset to 1.21 I'll do this.

> Merging 1.22 into 1.23.

The rebase was a recovery from a deadend.  I originally wanted to just force reset 1.23 to the rebased 1.22 on top of 1.21.  I can merge 1.21 into the 1.22 base branch here instead of the rebase if you don't have merge permissions to reset to 1.21.

**Comment by jennijuju** [comment]
should we close this?

**Pull request closed without merging**
