### PR TITLE
fix(f3): send the last gpbft message for each new participant

### PR DESCRIPTION
**Pull request by Stebalien**
## Proposed Changes

Send the last gpbft message for each new participant.

Otherwise, we can get into a situation where everyone is waiting for the next round to participate, but we'll never get there because not enough participants acted in the current round.

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [x] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [x] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
I'm going to write an itest where:

1. One node participates from the beginning.
2. Later, all the other nodes start participating.

**Comment by Stebalien** [comment]
I'm going to have to refactor a few things to make this testable. I'd prefer to merge this as-is and merge the test later after the refactor.

**Review by Kubuxu — APPROVED** [review]
Change SGWM but itests seem unhappy.

**Comment by Stebalien** [comment]
The tests have been failing across all the F3 tests regardless.

**Pull request merged**
