### PR TITLE
there is no real correlation between challenge count and len(winners)

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
This was causing posts to fail when len(winners) != ceil(sectorCount/25). Which basically meant all fallback posts (except for the first one) failed, and election posts fail after you have 25 sectors, unless you win two tickets.

**Comment by sternhenri** [comment]
Interesting. What was the rationale behind putting this in in the first place? Trying to understand whether anything should be done on my end...

**Comment by magik6k** [comment]
I misunderstood those 2 things as being somehow related / the same thing coming from different places.

**Comment by sternhenri** [comment]
Understood! I mean they are related in that len(winners) <= challCount obviously, but beyond that, no deeper relationship other than a set probability that a giveen challenge will win.

**Pull request merged**
