### PR TITLE
build: release Lotus node|miner v1.30.0 

### PR DESCRIPTION
**Pull request by rjan90**
## Related Issues
https://github.com/filecoin-project/lotus/issues/12480

## Proposed Changes
Update changelog and versions for v1.30.0.

## Additional Info
Opened the same changes https://github.com/filecoin-project/lotus/pull/12677, but for some reason that never created the draft releases automatically

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title conforms with [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions)
- [x] Update CHANGELOG.md or signal that this change does not need it per [contribution conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

### CODE REVIEW

**Review by masih — APPROVED** [review]

**Comment by masih** [comment]
> if we can skip this check and just publish the tags manually? Or if this is worth looking into more deeply?

I think we should take a closer look. I am not sure why it is failing.

**Comment by rjan90** [comment]
> I think we should take a closer look. I am not sure why it is failing.

Pushed a test where I downgraded Filecoin-FFI to v1.30.0-rc2, just to see if that is where the issue lies

**Comment by masih** [comment]
> Pushed a test where I downgraded Filecoin-FFI to v1.30.0-rc2, just to see if that is where the issue lies

It's not looking any better. I wonder if something has changed in the github actions runners?

**Comment by Stebalien** [comment]
We shouldn't even be _building_ the FFI here, we should be using pre-built assets. I think the issue is that we're trying to build a universal binary on macos-13 (x86) when we usually build on `macos-latest` (`macos-14`).

**Comment by Stebalien** [comment]
> 2024-11-06T15:46:32.8483500Z + echo '[download_release_tarball] failed to determine release tag'
2024-11-06T15:46:32.8484670Z [download_release_tarball] failed to determine release tag

**Comment by rjan90** [comment]
Drafts published: 
- https://github.com/filecoin-project/lotus/releases/tag/untagged-ed102ca7c4f9b6bae9e8
- https://github.com/filecoin-project/lotus/releases/tag/untagged-5d573ab02bf41563caab

**Comment by masih** [comment]
> We shouldn't even be _building_ the FFI here, we should be using pre-built assets.

Yeah :+1: but what changed since the last release?

**Pull request merged**
