### PR TITLE
Splitstore Garbage Collection

### PR DESCRIPTION
**Pull request by vyzo**
Implements online coldstore chain pruning and garbage collection with the `lotus chain prune` command.

See #6577  for discussion.

From the README:
The coldstore can be pruned and garbage collection using the `lotus chain prune` command.
Note that the command initiates pruning, but runs asynchronously as it can take a long time to
complete.

By default, pruning keeps all chain reachable object; the user however has the option to specify
a retention policy for old state roots and message receipts with the `--retention` option.
The value is an integer with the following semantics:
- If it is -1 then all state objects reachable from the chain will be retained in the coldstore.
  This is the (safe) default.
- If it is 0 then no state objects that are unreachable within the compaction boundary will
  be retained in the coldstore.
  This effectively throws away all old state roots and it is maximally effective at reclaiming space.
- If it is a positive integer, then it's the number of finalities past the compaction boundary
  for which chain-reachable state objects are retained.
  This allows you to keep some older state roots in case you need to reset your head outside
  the compaction boundary or perform historical queries.

During pruning, unreachable objects are deleted from the coldstore. In order to reclaim space,
you also need to specify a gargage collection policy, with two possible options:
- The `--online-gc` flag performs online garbage collection; this is fast but does not reclaim all
  space possible.
- The `--moving-gc` flag performs moving garbage collection, where the coldstore is moved,
  copying only live objects. If your coldstore lives outside the `.lotus` directory, e.g. with
  a symlink to a different file system comprising of cheaper disks, then you can specify the
  directory to move to with the `--move-to` option.
  This reclaims all possible space, but it is slow and also requires disk space to house the new
  coldstore together with the old coldstore during the move.

### CODE REVIEW

**Comment by vyzo** [comment]
rebased for changes in the base branch.

**Comment by vyzo** [comment]
rebased on master.

**Comment by vyzo** [comment]
I'll rebase and resolve the gen conflicts when we are ready to merge.

**Comment by Stebalien** [comment]
This needs integration tests. I.e., tests where we trigger GC _while_ computing a tipset or at least something that _approximates_ computing a tipset (i.e. a bunch of reads, then `vm.Copy`). Ideally:

1. Start GC before computing, and during.
2. End GC during and after.

VM execution doesn't _just_ write blocks, it makes a bunch of assumptions about what we have and what we don't have.

**Comment by vyzo** [comment]
Agreed; for now I am testing in a live node, but we definitely want a proper integration test.
I propose we add it to the Harness test effort outlined in #6725 

How does it sounds to you? 
It something we can reasonably handle without time pressure after the v1.11.1 release code freeze.

**Comment by Stebalien** [comment]
It's really a waste of time to review until there are tests. Testing on a node isn't likely to trigger the conditions we care about.

**Comment by Stebalien** [comment]
(also, let's please break this into two PRs: one that refactors (splits files), then one that makes the actual change)

**Comment by vyzo** [comment]
Agreed with the sentiment, following our sync discussion.
I'll cherry-pick the refactor out for easy review, and then the plan is to write a good enough integration test. 
If we can get it done before the deadline, great.
If not, we don't have to ship it now, and people who are willing to take the risk can always use the pr directly.

**Comment by BlocksOnAChain** [comment]
@vyzo should we close this one since it's related to 1.11.1 which is out?
FYI: @jennijuju

**Comment by vyzo** [comment]
no, its in draft for a reason.

**Comment by magik6k** [comment]
Done in https://github.com/filecoin-project/lotus/pull/9056

**Pull request closed without merging**
