### PR TITLE
Feat: Lotus cli: actor: Support move partition command to move partitions' deadline

### PR DESCRIPTION
**Pull request by mb1896**
## Related Issues
https://github.com/filecoin-project/lotus/issues/11272

## Proposed Changes
Add `move-partition` subcommand to `lotus-miner actor` command.

## Additional Info
Still waiting for corresponding actor changes to merge https://github.com/filecoin-project/builtin-actors/pull/1326/files

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

# Example usage
Before
```
$ ./lotus-miner proving deadlines
Miner: t01000
deadline  partitions  sectors (faults)  proven partitions
0         0           0 (0)             0
1         0           0 (0)             0
2         0           0 (0)             0
3         0           0 (0)             0
4         0           0 (0)             0
5         0           0 (0)             0
6         0           0 (0)             0
7         0           0 (0)             0
8         0           0 (0)             0
9         0           0 (0)             0
10        0           0 (0)             0
11        0           0 (0)             0
12        0           0 (0)             0
13        0           0 (0)             0
14        0           0 (0)             0  (current)
15        0           0 (0)             0
16        0           0 (0)             0
17        0           0 (0)             0
18        0           0 (0)             0
19        0           0 (0)             0
20        1           2 (0)             0
21        0           0 (0)             0
22        0           0 (0)             0
23        0           0 (0)             0
24        0           0 (0)             0
25        0           0 (0)             0
26        0           0 (0)             0
27        0           0 (0)             0
28        0           0 (0)             0
29        0           0 (0)             0
30        0           0 (0)             0
31        0           0 (0)             0
32        0           0 (0)             0
33        0           0 (0)             0
34        0           0 (0)             0
35        0           0 (0)             0
36        0           0 (0)             0
37        0           0 (0)             0
38        0           0 (0)             0
39        0           0 (0)             0
40        0           0 (0)             0
41        0           0 (0)             0
42        0           0 (0)             0
43        0           0 (0)             0
44        0           0 (0)             0
45        0           0 (0)             0
46        0           0 (0)             0
47        0           0 (0)             0
```

Then use
```
$ ./lotus-miner actor move-partitions --partition-indices 0 --orig-deadline 20 --dest-deadline 17
Miner: t01000
Moving 1 paritions
MovePartitions Message CID: bafy2bzaceaxz7ujzanqq5k5yhvszzgqyydxhylhfy7vrcywv4rbi76j2zicfk
Waiting for block confirmation...
Move partition confirmed
```

Check deadline has been moved

```
$ ./lotus-miner proving deadlines                                                                
Miner: t01000
deadline  partitions  sectors (faults)  proven partitions
0         0           0 (0)             0
1         0           0 (0)             0
2         0           0 (0)             0
3         0           0 (0)             0
4         0           0 (0)             0
5         0           0 (0)             0
6         0           0 (0)             0
7         0           0 (0)             0
8         0           0 (0)             0
9         0           0 (0)             0
10        0           0 (0)             0
11        0           0 (0)             0
12        0           0 (0)             0
13        0           0 (0)             0
14        0           0 (0)             0
15        0           0 (0)             0  (current)
16        0           0 (0)             0
17        1           2 (0)             0
18        0           0 (0)             0
19        0           0 (0)             0
20        0           0 (0)             0
21        0           0 (0)             0
22        0           0 (0)             0
23        0           0 (0)             0
24        0           0 (0)             0
25        0           0 (0)             0
26        0           0 (0)             0
27        0           0 (0)             0
28        0           0 (0)             0
29        0           0 (0)             0
30        0           0 (0)             0
31        0           0 (0)             0
32        0           0 (0)             0
33        0           0 (0)             0
34        0           0 (0)             0
35        0           0 (0)             0
36        0           0 (0)             0
37        0           0 (0)             0
38        0           0 (0)             0
39        0           0 (0)             0
40        0           0 (0)             0
41        0           0 (0)             0
42        0           0 (0)             0
43        0           0 (0)             0
44        0           0 (0)             0
45        0           0 (0)             0
46        0           0 (0)             0
47        0           0 (0)             0
```

### CODE REVIEW

**Review by snadrus — APPROVED** [review]

**Comment by rjan90** [comment]
Testing plan:

### General:

- [ ]  Run the disputer when completing these tasks

### FIP specific:

- [ ]  Check that CLI-command for moving partition / partitions works as expected:

Successes:
- [ ]  Check that moving a single partition (1) from a deadline to another which proving period is in 24 hours after the partitions last proving deadline works
    - [ ]  WindowPoSt functions for partition moved from original deadline to new deadline
    - [ ]  Check that compact partitions works for moved partition
    - [ ]  Check that failing and recovering the partition in the new deadline works
    
 The cmd should fail when:
 - [ ]  Check that moving a single partition (1) from a deadline to another which proving period is beyond 24 hours after the partitions last proving deadline fails.
- [ ]  Check that moving multiple partitions in a deadline to another which proving period is in 24 hours after the partitions last proving period fails.
- [ ]  Check that a WindowPoSt-partition with failed sectors is unable to be moved.

Some edge-cases we want to test:

Move a partition from a deadline to another then:

- [ ] Fault & recover sectors in that partition.
- [ ] Fault & terminate sectors in that partition.
- [ ] Directly terminate non-faulty sectors in that partition.
- [ ] Fault and let sectors expire as faulty in that partition.

**Comment by jennijuju** [comment]
@rjan90 thank you for the test plan - can we also add
- try to merge partitions to a single deadline till a deadline hits `max_partitions_per_deadline` and it should fail?

**Comment by BaiYuTest** [comment]
1. Checked continuous move：move a partition from A deadline to B deadline  ，then move that partition from B deadline to C deadline.

2. Checked repeat move： move a partition from A deadline to B deadline successful，then move the partition from A deadline to B deadline again.
./damocles-manager util sealer sectors move-partitions --miner t01011 --partition-indices 0 --orig-deadline 0 --dest-deadline 20 --really-do-it
compacting 1 paritions
Requested compact partitions in message xxxxx
First movement：
Partition Index:           100
        All Sectors:               2
        All Sector Numbers:         [0 1]
        Live Sectors:              2
        Live Sector Numbers:        [0 1]
        Active Sectors:            2
        Active Sector Numbers:      [0 1]
        Faulty Sectors:            0
        Faulty Sector Numbers:      [0]
        Recovering Sectors:        0
        Recovering Sector Numbers:  []
   
Second movement：   
Partition Index:           100
        All Sectors:               2
        All Sector Numbers:         [0 1]
        Live Sectors:              2
        Live Sector Numbers:        [0 1]
        Active Sectors:            2
        Active Sector Numbers:      [0 1]
        Faulty Sectors:            0
        Faulty Sector Numbers:      [0]
        Recovering Sectors:        0
        Recovering Sector Numbers:  []
  Partition Index:           101
        All Sectors:               0
        All Sector Numbers:         [0 0]
        Live Sectors:              0
        Live Sector Numbers:        [0 0]
        Active Sectors:            0
        Active Sector Numbers:      [0 0]
        Faulty Sectors:            0
        Faulty Sector Numbers:      [0]
        Recovering Sectors:        0
        Recovering Sector Numbers:  []

**Comment by BaiYuTest** [comment]
The following test case scenario passed using venus：
- [x] Check that moving a single partition from a deadline to another which proving period is in 24 hours after the partitions last proving deadline works, and WindowPoSt works.
- [x] Check that moving a single partition from a deadline to another which proving period is beyond 24 hours after the partitions last proving deadline fails.
- [x] Check that moving multiple partitions from a deadline to another which proving period is in 24 hours after the partitions last proving deadline works, and WindowPoSt works.
- [x] Check that moving faulty paritions are not allowed.  
- [x] Check that moving unproven paritions are not allowed. 
- [x] Check that faulty sectors in a partition in the new deadline works after it has been proven after the move.
- [x] Check that moving a single partition from A deadline to B deadline, then compact the blank partition in A deadline works.
- [x] Check that moving a single partition from A deadline to B deadline, then moving that partition from B deadline to C deadline, and WindowPoSt works.
- [x] Check that moving an unexisted partition fails.

We also want to test：
- [ ] Terminate 
- [ ] Expired sectors

**Pull request merged**
