### PR TITLE
fix: eth: remove trace sanity check

### PR DESCRIPTION
**Pull request by Stebalien**
## Proposed Changes

We added this check as a self-test to make sure that the message indices in our trace matched up with those in the block. Unfortunately, this only works for blocks on the main-chain, and breaks tracing of uncle blocks (and tracing of head).

## Checklist

Before you mark the PR ready for review, please make sure that:

- [x] Commits have a clear commit message.
- [x] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [x] New features have usage guidelines and / or documentation updates in
  - [x] [Lotus Documentation](https://lotus.filecoin.io)
  - [x] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [x] CI is green

### CODE REVIEW

**Comment by Stebalien** [comment]
Hm. Apparently we're hitting this check in production. I'll have to debug this.

**Comment by Stebalien** [comment]
Nevermind, this code was the problem. We are attempting to lookup the _parent_ messages by looking up the "next" epoch's tipset, then looking backwards. But, if we have a null tipset, we'd look up the wrong tipset.

So, removing this code is the correct thing to do.

**Review by hawkaa — APPROVED** [review]
LGTM!

**Comment by fridrik01** [comment]
@Stebalien So this failed when we were tracing a block which following tipset was a null tipset? Could we have a method for fetching the next non-null tipset for a given epoch (it may be useful in other cases) and then we could have sanity checks like this

**Comment by Stebalien** [comment]
@fridrik01 this logic doesn't work in the presence of forks either. E.g.:

Given:

```
A <- B <- C     <-- C is head
 \
  \- X <- Y     <-- fork
```

If we try to trace `X`, we'll end up looking up `C` as the next block instead of `Y`.

**Review by fridrik01 — APPROVED** [review]

**Pull request merged**
