### PR TITLE
update ffi to code with blst fixes

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by arajasek** [comment]
I don't understand how we're building this, but will we need to also update the `extern/fil-blst` and / or `./extern/fil-blst/blst` Lotus deps?

**Comment by whyrusleeping** [comment]
well, the blst repo apparently contains a bunch of different things, when we import it in go, we don't use the code that actually contains the fix. The rust code is what imports the c++ code that has the code being fixed. So our imports in the go side don't really change.

At least, as far as i understand.

**Comment by arajasek** [comment]
yeah, i don't understand either...would there be an argument to "update anyway"? idkkk.

**Comment by dignifiedquire** [comment]
Yeah this is the "right" way for the moment, though it will get better soon(tm)

**Comment by jennijuju** [comment]
does this fix #3826 ?

**Review by Kubuxu — APPROVED** [review]

**Review by magik6k — APPROVED** [review]

**Comment by magik6k** [comment]
> does this fix #3826 ?

Probably not

**Pull request merged**
