### PR TITLE
paych: modify `lotus paych voucher best-spendable` to output _all_ best vouchers

### PR DESCRIPTION
**Pull request by dirkmc**
Depends on https://github.com/filecoin-project/lotus/pull/3043

Currently `lotus paych voucher best-spendable` only outputs a single voucher.

This PR modifies the command to output the best voucher in each lane, and also makes the output consistent with
`lotus paych voucher list`

### CODE REVIEW

**Comment by dirkmc** [comment]
When I run 
`go test ./cli -v -run TestPaymentChannels`

I get
```
    TestPaymentChannels: paych_test.go:274: 
        	Error Trace:	paych_test.go:274
        	            				paych_test.go:92
        	Error:      	Received unexpected error:
        	            	collect message execution failed (exit code 7)
        	Test:       	TestPaymentChannels
--- FAIL: TestPaymentChannels (10.13s)
```

It seems that exit code 7 is [SysErrOutOfGas](https://github.com/filecoin-project/specs-actors/blob/master/actors/runtime/exitcode/reserved.go#L37). However I [send 10^18 worth of funds](https://github.com/filecoin-project/lotus/pull/3146/files#diff-9f5a507a91794e6124181b5a85795afaR216) to the actor that calls `collect` so I'm not sure why it would be out of gas.

**Comment by whyrusleeping** [comment]
@Kubuxu any idea here?

**Comment by dirkmc** [comment]
This is the test:
https://github.com/filecoin-project/lotus/blob/d1592b01c385a5dbc7ec73fcf51a4d95ab3fed0c/cli/paych_test.go#L48
1. Starts a block miner and two nodes (channel creator and receiver).
2. Sends 1e18 from the creator to the receiver
3. Calls creator: `paych get <creator> <receiver> 100000`
    returns `<channel>`
4. Calls creator: `paych voucher create <channel> 100`
    returns `<voucher>`
5. Calls receiver: `paych voucher add <channel> <voucher>`
6. Calls creator: `paych settle <channel>`
7. Waits for chain to reach settle height:
   12 hours of blocks  =
   (12 * 60 * 60 / 30) = 1440 blocks
   (Note that we're using a 5ms block time for the test so this takes about 10 seconds)
8. Calls receiver: `paych collect <channel>`
   This is where we get `SysErrOutOfGas`

**Comment by Kubuxu** [comment]
So the reason for `OutOfGas` is that we get 76k gas refund. Not sure how it solve it.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
