### PR TITLE
miner: Winning PoSt Warmup

### PR DESCRIPTION
**Pull request by magik6k**
Should address https://github.com/filecoin-project/rust-fil-proofs/issues/1355

### CODE REVIEW

**Comment by magik6k** [comment]
(works on my miner)

**Review by Kubuxu — APPROVED** [review]

**Comment by Kubuxu** [comment]
Tests failed in weird way.

**Comment by PatrickDeuse** [comment]
just a quick follwo up question

this prints

`{"level":"info","ts":"2020-11-16T14:23:01.036Z","logger":"storageminer","caller":"storage/miner.go:261","msg":"GenerateWinningPoSt took 5.397016086s"}`

on startup now?

**Comment by ffteng47** [comment]
same question.what does this mean i missed a block mined?
2020-11-22T15:13:00.724+0800    ^[[34mINFO^[[0m miner   miner/warmup.go:75      winning PoSt warmup successful  {"took": 4.693931498}

**Comment by PatrickDeuse** [comment]
it just means that the miner performs a GPU warmup to avoid delays later when actually calculating a block @ffteng47 

at least i think that is what it is doing

**Comment by karalabe** [comment]
Doesn't work, or at least not fully

```
{"level":"info","ts":"2020-11-25T04:13:40.626+0200","logger":"miner","caller":"miner/miner.go:446","msg":"mined new block","cid":"bafy2bzaced3bwp3milnk3uf2pro7cjtpu7hezmsn5i2bm32tqaf2ysvvvywgq","height":"265466","miner":"f019100","parents":["f021525","f03367","f060805","f05315","f023198"],"took":64.479446023}
{"level":"warn","ts":"2020-11-25T04:13:40.626+0200","logger":"miner","caller":"miner/miner.go:448","msg":"CAUTION: block production took longer than the block delay. Your computer may not be fast enough to keep up","tMinerBaseInfo ":0.005823102,"tDrand ":0.00000008,"tPowercheck ":0.00000007,"tTicket ":0.001790605,"tSeed ":0.000002706,"tPending ":64.349789092,"tCreateBlock ":0.122040368}
{"level":"warn","ts":"2020-11-25T04:13:40.626+0200","logger":"miner","caller":"miner/miner.go:267","msg":"mined block in the past","block-time":"2020-11-25T04:13:00.000+0200","time":"2020-11-25T04:13:40.626+0200","difference":40.626337785}
```

**Comment by kwuaint** [comment]
The  **winning** post's "tPending" consume too many time, since the GPU is running the **window** post simultaneously.

**Pull request merged**
