### PR TITLE
storageminer: Improve CLI UX

### PR DESCRIPTION
**Pull request by magik6k**
Before:

before

After:
after

### CODE REVIEW

**Comment by Kubuxu** [comment]
Maybe use: https://github.com/mattn/go-isatty to automatically disable colors when piping.

**Comment by magik6k** [comment]
isatty doesn't work with `watch`, which doesn't support colors by default apparently

**Comment by Kubuxu** [comment]
@magik6k you mean it still detects it as tty?

**Comment by magik6k** [comment]
> @magik6k you mean it still detects it as tty?

Yes, even without `-c`, which is why I didn't use it

**Pull request merged**
