### PR TITLE
Fix some failed precommit handling

### PR DESCRIPTION
**Pull request by arajasek**
I think this is correct?

Thanks to @Arctic in the Filecoin slack for the report.

### CODE REVIEW

**Comment by magik6k** [comment]
Can you share more context on this issue?

**Comment by arajasek** [comment]
@magik6k I think it's just a question of whether this is the correct thing to be doing. 

- Is the boolean returned by `checkPreCommitted` an indication of whether the sector has already precommitted? If so, I think we should be returning false in the error cases, and true otherwise?

- If I'm understanding it correctly, the `log.Warn("sector %d is precommitted on chain, but we don't have precommit message", sector.SectorNumber)` should be triggered if we _didn't_ have the `PreCommitMessage` field in the `SectorInfo` (that is if it _is_ `nil`, not if it _isn't_).

Might be wrong on both counts 🤷‍♀️

**Comment by whyrusleeping** [comment]
@magik6k context is here: https://filecoinproject.slack.com/archives/C0179RNEMU4/p1598926390173100

someone claims theyve found a silly bug but doesnt really say what it is. they seem really intent on being 'helpful'

**Review by magik6k — APPROVED** [review]
This fix looks correct, not sure what how this code ended up in this shape

**Pull request merged**
