### PR TITLE
Modify vesting schedule post-calico

### LINKED ISSUE #4660: Fix circulating supply
One of the entries in the circulating supply lookup table isn't accurate and needs to be fixed. We might also cleanup some of the circ supply code as part of this issue.

### PR DESCRIPTION
**Pull request by arajasek**
There was an accounting mistake in the vesting table. It was reported but not fixed because of timeline and fixing it earlier will mean a spike in collateral for miners. This PR upgrades the vesting table to more closely match the actual multisig vesting.

Fixes #4660

### CODE REVIEW

**Comment by arajasek** [comment]
Needs ✅  from @whyrusleeping

**Review by magik6k — APPROVED** [review]
Upgrade logic looks good

**Review by whyrusleeping — APPROVED** [review]
these numbers are slightly different than i'd expect, but i'm guessing @zixuanzh has some reason for this

**Comment by zixuanzh** [comment]
What do you mean? This should be as transparent as possible with no room for meddling.

**Comment by arajasek** [comment]
> these numbers are slightly different than i'd expect, but i'm guessing @zixuanzh has some reason for this

the reason is likely that @whyrusleeping is bad at excel and calculates bad numbers

**Pull request merged**
