### PR TITLE
change api to port

### PR DESCRIPTION
**Pull request by zgfzgf**
#3912

lotus-miner run --port=5432

### CODE REVIEW

**Comment by travisperson** [comment]
Any reason you want to do this? The `api` is meant to signify that it's setting the api port. Both the lotus daemon and miner also run a libp2p host. Changing this to just `port` makes it ambiguous. It would be better to just add usage text that provide more context that it's the port that the api will listen on.

**Comment by zgfzgf** [comment]
@travisperson  
#3912 

func GetAPIInfo(ctx *cli.Context, t repo.RepoType) (APIInfo, error) {
	// Check if there was a flag passed with the listen address of the API
	// server (only used by the tests)

	apiFlag := flagForAPI(t)   // "api"
	if ctx.IsSet(apiFlag) {
		strma := ctx.String(apiFlag)
		strma = strings.TrimSpace(strma)

		apima, err := multiaddr.NewMultiaddr(strma)
		if err != nil {
			return APIInfo{}, err
		}
		return APIInfo{Addr: apima}, nil
	}

apiFlag is “api" 
Here we will take the api of miner as the api of lotus daemon
And the format of api here is not only port, it should be "/ip4/127.0.0.1/tcp/1234/http"
So change the api of miner and otus daemon to port

**Comment by zgfzgf** [comment]
Keep the api at the same time

**Comment by zgfzgf** [comment]
lotus-miner run -h
NAME:
   lotus-miner run - Start a lotus miner process

USAGE:
   lotus-miner run [command options] [arguments...]

OPTIONS:
   --api value           lotus daemon api format: ip4/127.0.0.1/tcp/1234
   --token value         lotus daemon api token
   --port value          (default: "2345")
   --enable-gpu-proving  enable use of GPU for mining operations (default: true)
   --nosync              don't check full-node sync status (default: false)
   --manage-fdlimit      manage open file limit (default: true)
   --help, -h            show help (default: false)


lotus-miner run  --api=/ip4/127.0.0.1/tcp/4321 --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.QfKx_PabtQo3THa1LJsmYqPgxEDkqHnQ3WnX_MSV0e

**Comment by zgfzgf** [comment]
Update code impact test example

Update later

**Pull request closed without merging**
