### PR TITLE
chore: libp2p: LOTUS_P2P_BOOTSTRAPPERS="" is valid setting

### PR DESCRIPTION
**Pull request by ribasushi**
Allows one to run
```
LOTUS_P2P_BOOTSTRAPPERS="" ./lotus daemon
```

and then connect to a chosen bootstrapper manually

### CODE REVIEW

**Comment by rvagg** [comment]
I'm a bit dubious about the need for this, can you explain a concrete use-case where this makes sense?

Also since #12592 is merged, could you rebase and we can look at CI again, because those failures are not known flakies.

**Comment by rjan90** [comment]
> The use case is testing.

@ribasushi Why can't you use the `lotus daemon --bootstrap` flag, if the plan is to test without bootstrappers?

**Comment by rjan90** [comment]
> If it is that much of a problem - just close the PR, I'll carry the fix locally.

I was hoping to understand the differences between using the `--bootstrap` flag and the environment variable for this purpose. There's no need for frustration; I'm simply looking for clarification.

**Comment by Stebalien** [comment]
This introduces a footgun because bash doesn't error on undefined variables. E.g., the following would disable bootstrapping and should likely just fail with an error:

```
export LOTUS_P2P_BOOTSTRAPPERS="$UNDEFINED_OR_MISSPELLED_VAR"
```

 I'd rather just stick with the current mechanism of `--bootstrap=false`. Not protecting bootstrappers if `--bootstrap=false` would also be reasonable but note: protection isn't the same thing as "peering", we won't automatically re-connect.

Closing for now given that "for testing" isn't really enough of a motivation in this case. We can reconsider if we find this causing an actual problem.

**Comment by Stebalien** [comment]
> I obviously disagree with this outcome and find it beneath this devteam.

If you disagree, please provide clear motivation (more than just "for testing"). Please _don't_ attack the team reviewing your PRs.

**Comment by Stebalien** [comment]
I've re-read this entire interaction multiple times and have no idea what you're talking about:

1. PR was submitted with no motivation provided.
2. Motivation was requested (as is _normal_ for all proposed changes). It's not obvious that "empty" is a valid/reasonable value here.
3. The provided motivation was a vague "for testing".
4. The counter-argument I provided is that this change introduces footgun. You elected to not continue the discussion (on slack) so I closed it.

Where is the pettiness? Why do you say that the team _maintaining_ this software doesn't have the right to ask for motivation for changes?

**Pull request closed without merging**
