### PR TITLE
Chore/blockstore nits

### PR DESCRIPTION
**Pull request by ribasushi**
Landing a few nits from a larger semi-abandoned refactor.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]
Thanks for catching this. I had thought we were actually GCing somewhere.

**Review by raulk — APPROVED** [review]
Consistent with my findings.

**Review by Kubuxu — APPROVED** [review]

**Comment by ribasushi** [comment]
@Kubuxu what's the "protocol" for merging such PRs? Just checking whether it is waiting on something from my side...

**Comment by Kubuxu** [comment]
Nah, it was waiting for someone to feel like pressing a button.

**Pull request merged**
