### PR TITLE
use O_RDWR to open paramfile

### LINKED ISSUE #685: error "checksum mismatch in param file" when lotus and lotus-storage-miner are started at the same time
if  lotus and lotus-storage-miner are started in the same (can be separated in future?) fresh machine  ,  error "checksum mismatch in param file" will always be prompted because two processes are trying read/write data from/into the same file under directory /var/tmp/filecoin-proof-parameters.

### PR DESCRIPTION
**Pull request by deaswang**
fix #685

### CODE REVIEW

**Comment by Kubuxu** [comment]
I think it would be better to use https://godoc.org/github.com/ipfs/go-fs-lock or https://godoc.org/go4.org/lock to lock the whole dir (by locking on the same file) when we are downloading something.

**Comment by whyrusleeping** [comment]
@laser can you look into porting this to the extracted paramfetch code? Its not entirely clear this PR is the best solution (i think it might end up downloading everything twice? not sure) but resolving 685 would be good, and that issue now belongs to that new repo

**Comment by whyrusleeping** [comment]
is this still an issue?

**Comment by magik6k** [comment]
paramfetch moved to https://github.com/filecoin-project/go-paramfetch

**Pull request closed without merging**
