### PR TITLE
Add options to set BlockProfileRate and MutexProfileFraction

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
We probably want to put this behind auth / make opt-in with an env var (this is exposed on the API port)

**Comment by Kubuxu** [comment]
It is behind POST request so the browser has no access to it.

**Comment by magik6k** [comment]
Sure, but other internet things do

**Comment by whyrusleeping** [comment]
I think its probably fine to say if youre exposing a lotus api publically, you should probably not expose a lotus api publically.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
